#!/bin/sh
# Builds a shar archive out of a build dir, with the parts
# residing in a directory 'tmp' at the same level as the build dir;
# If tmp doesn't exist, it creates it.
# This script will reside at the top level of the build dir;
# Invoke this with any path to this script 
# The files of the shar are limited to 500K to make it through
# the limitations of some mail gateways.
#
# Command line args:
#    -to  <email_addr> [optional] - mailer file sends to this address
#	if omitted, mails to: build-master@als.com
#    -from <email_addr> [optional] - passed to shar
#	if omitted, attempts to determine address & account;
#	otherwise, fills in with: default

echo Building shar archive of alsprolog build directory

sharme_prog=$0
call_path=`echo $sharme_prog|sed 's%/[^/][^/]*$%%'`
echo Starting in `pwd`  -- call_path = $call_path

if test $call_path = $sharme_prog ; then
   alsp_dir=`pwd`
else
   if [ `echo $call_path | sed -e 's/^\(.\).*/\1/'` = "/" ]; then	
      echo Path $call_path is absolute ; alsp_dir=$call_path
   else	
      echo Path $call_path is relative ; alsp_dir=`pwd`/$call_path
   fi
fi
echo alsp_dir = $alsp_dir

echo Perfomring super cleanup
make superclean
echo Super cleanup finished

domain=`domainname`
host=`hostname`

./bld-port/alspro sharalsp -p -alsp $alsp_dir $* -dom $domain -host $host
#./bld-port/alspro sharalsp -g sharbld -p -alsp $alsp_dir $* -dom $domain -host $host
