# TODO: Fix cygwin-unix build:    - OS: unix
environment:
  matrix:
    - OS: win32

cache:
  - C:/cygwin/var/cache/setup -> .appveyor.yml
  - C:/bundle -> .appveyor.yml

install:
  - SET PATH=C:\Ruby26\bin;%PATH%
  - SET BUNDLE_PATH=C:\bundle
  - "C:/cygwin/setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup 
-P 
libcrypt-devel,mingw64-i686-libgcrypt,mingw64-i686-curl,tcl-tk-devel,mingw64-i686-tcl,mingw64-i686-tk,zip,php,procps"

build_script:
  - C:\Cygwin\bin\bash -l %APPVEYOR_BUILD_FOLDER%\cibuild

on_finish:
  - ps: |
        if ( $env:APPVEYOR_RE_BUILD -eq $true -AND $env:APPVEYOR_REPO_BRANCH -ne 'master' ) {
          $blockRdp = $true
          iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
        }
