language: C
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - gcc-multilib
    - tk-dev:i386

script:
  - cd core/unix ; make test

# TODO: work out tk-dev:i386 dependency to allow full build
