language: C
dist: trusty
sudo: required

os:
  - linux
  - osx

# Use aptitude/dpkg to force-install 32-bit versions of tcl/tk dev.
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]
  then
    sudo dpkg --add-architecture i386
    sudo apt-get -yq update
    sudo apt-get -yq install gcc-multilib
    sudo aptitude -yq install tcl-dev:i386
    sudo aptitude -yq install libtk8.6:i386
    apt-get download tk8.6-dev:i386 tk-dev:i386
    sudo dpkg -i --force-all *.deb
  fi

script:
  - cd unix && make && make test
