language: C
dist: trusty
sudo: true

os:
  - linux
  - osx

before_install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]
  then
    sudo dpkg --add-architecture i386
    sudo apt-get -yq update
    sudo apt-get -yq install gcc-multilib
    sudo aptitude -yq install tcl-dev:i386
    sudo aptitude -yq install tk-dev:i386
  fi

script:
  - cd unix
  - make && make test
