language: C
#dist: bionic

# https://docs.travis-ci.com/user/caching/#cache-rvm-ruby-version-for-non-ruby-projects
cache:
    directories:
     - /home/travis/.rvm/

os:
  - linux
  - osx

script:
  - ./cibuild
