language: C
dist: trusty
sudo: true

os:
  - linux
  - osx

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -yq update
  - sudo aptitude -yq install gcc-multilib tk-dev:i386

script:
  - cd unix
  - make && make test
