language: C
dist: trusty
sudo: true

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386                               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -yq update                                         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo aptitude -yq install gcc-multilib tcl-dev:i386 tk-dev:i386 ; fi

script:
  - cd unix
  - make && make test
