language: Ruby
dist: trusty
sudo: required

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors from html-proofer

os:
  - linux
  - osx

# Use aptitude/dpkg to force-install 32-bit versions of tcl/tk dev.
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]
  then
    sudo dpkg --add-architecture i386
    sudo apt-get -yq update
    sudo apt-get -yq install gcc-multilib
    sudo aptitude -yq install tcl-dev:i386
    sudo aptitude -yq install libtk8.6:i386
    sudo aptitude -yq install libx11-dev:i386
    sudo aptitude -yq install libcurl4-openssl-dev:i386
    sudo apt-get -yq install php5-cli
    apt-get download tk8.6-dev:i386 tk-dev:i386
    sudo dpkg -i --force-all *.deb
    rm *.deb
    export CFLAGS=--std=gnu99
    export PHP=php5
  fi

script:
  - ./cibuild
