#!/bin/bash

set -eux -o pipefail

cd "$(dirname "$0")"


case "$(uname)" in
    "CYGWIN"*)  OS=win32 ;;
    *)          OS=unix
                # Report common warnings as errors
                export CFLAGS="${CFLAGS:-} -Werror=all"
                ;;
esac

pushd $OS
make
if [[ $OS == 'unix' ]]
then
	make testdocs
fi
make test

# Test clean and check that no source files are modified
make distclean
[ -z "$(git status --short --ignored)" ]

popd
