#!/bin/bash

# Automagically calculate project version number from git tags

# Archive hash and description set by git-archive via export-subst in .gitattributes
ARCHIVE='$Format:%h%d$'

# Examples expansions:
#ARCHIVE='09f863b (tag: v3.2.0)'
#ARCHIVE='2ea0e4a (HEAD -> master)'

# Use archive tag, if found
if [[ $ARCHIVE =~ tag:\ ([^\)]+)\) ]]
then
	VERSION=${BASH_REMATCH[1]}
	
# Use archive branch and hash, if found
elif [[ $ARCHIVE =~ ([^ ]+)\ \(.*-\>\ ([^\),]+).*\) ]]
then
	VERSION=${BASH_REMATCH[2]}-${BASH_REMATCH[1]}

# Use git-describe for working trees
elif [[ $(git rev-parse --is-inside-work-tree) == 'true' ]]
then
	VERSION=$(git describe --tags --dirty)
else
	VERSION='unknown'
fi

# Strip leading 'v' if found
if [[ ${VERSION:0:1} == 'v' ]]
then
	VERSION=${VERSION:1}
fi

echo $VERSION
