#define TK_CALL         	1	/* call */
#define TK_OCALL        	2	/* callWithDelayedInterrupt */
#define TK_DBG_CALL     	3	/* dbg_call */
#define TK_SCOLON3      	4	/* $semicolon */
#define TK_COMMA3       	5	/* $comma */
#define TK_IFARROW3     	6	/* $arrow */
#define TK_SCOLON       	7	/* ; */
#define TK_COMMA        	8	/* , */
#define TK_COLON        	9	/* : */
#define TK_VBAR         	10	/* | */
#define TK_IFARROW      	11	/* -> */
#define TK_CUT          	12	/* ! */
#define TK_IS           	13	/* is */
#define TK_LESS         	14	/* < */
#define TK_GRT          	15	/* > */
#define TK_LEQ          	16	/* =< */
#define TK_GEQ          	17	/* >= */
#define TK_ZEBRA        	18	/* =:= */
#define TK_ZEBRA2       	19	/* =\= */
#define TK_HEAPUSED     	20	/* heapused */
#define TK_CPUTIME      	21	/* cputime */
#define TK_REALTIME     	22	/* realtime */
#define TK_RANDOM       	23	/* random */
#define TK_NOT          	24	/* not */
#define TK_BACKSLASH    	25	/* \ */
#define TK_ABS          	26	/* abs */
#define TK_SIN          	27	/* sin */
#define TK_SINH         	28	/* sinh */
#define TK_COS          	29	/* cos */
#define TK_COSH         	30	/* cosh */
#define TK_TAN          	31	/* tan */
#define TK_TANH         	32	/* tanh */
#define TK_ASIN         	33	/* asin */
#define TK_ACOS         	34	/* acos */
#define TK_ATAN         	35	/* atan */
#define TK_SQRT         	36	/* sqrt */
#define TK_EXP          	37	/* exp */
#define TK_EXP10        	38	/* exp10 */
#define TK_LOG          	39	/* log */
#define TK_LOG10        	40	/* log10 */
#define TK_FLOOR        	41	/* floor */
#define TK_ROUND        	42	/* round */
#define TK_CEIL         	43	/* ceil */
#define TK_ERF          	44	/* erf */
#define TK_ERFC         	45	/* erfc */
#define TK_GAMMA        	46	/* gamma */
#define TK_J0           	47	/* j0 */
#define TK_J1           	48	/* j1 */
#define TK_Y0           	49	/* y0 */
#define TK_Y1           	50	/* y1 */
#define TK_TRUNC        	51	/* trunc */
#define TK_PLUS         	52	/* + */
#define TK_MINUS        	53	/* - */
#define TK_ATAN2        	54	/* atan2 */
#define TK_FMOD         	55	/* fmod */
#define TK_HYPOT        	56	/* hypot */
#define TK_JN           	57	/* jn */
#define TK_YN           	58	/* yn */
#define TK_STAR         	59	/* * */
#define TK_SLASHSLASH   	60	/* // */
#define TK_DIV          	61	/* div */
#define TK_MOD          	62	/* mod */
#define TK_BAND         	63	/* /\ */
#define TK_BOR          	64	/* \/ */
#define TK_BXOR         	65	/* xor */
#define TK_LSHFT        	66	/* << */
#define TK_RSHFT        	67	/* >> */
#define TK_SLASH        	68	/* / */
#define TK_IDCL         	69	/* :: */
#define TK_INE          	70	/* <> */
#define TK_IAEQ         	71	/* @= */
#define TK_ISBI         	72	/* <= */
#define TK_IBIP         	73	/* => */
#define TK_2ST          	74	/* ** */
#define TK_HAT          	75	/* ^ */
#define TK_XFX          	76	/* xfx */
#define TK_XFY          	77	/* xfy */
#define TK_YFX          	78	/* yfx */
#define TK_FX           	79	/* fx */
#define TK_FY           	80	/* fy */
#define TK_XF           	81	/* xf */
#define TK_YF           	82	/* yf */
#define TK_RIF          	83	/* :- */
#define TK_QUEST        	84	/* ?- */
#define TK_PRW          	85	/* --> */
#define TK_EQ           	86	/* = */
#define TK_UNIV         	87	/* =.. */
#define TK_ID           	88	/* == */
#define TK_UID          	89	/* \== */
#define TK_ALS          	90	/* @< */
#define TK_AGR          	91	/* @> */
#define TK_ALEQ         	92	/* @=< */
#define TK_AGEQ         	93	/* @>= */
#define TK_DOT          	94	/* . */
#define TK_LBRAC        	95	/* [ */
#define TK_RBRAC        	96	/* ] */
#define TK_LPAREN       	97	/* ( */
#define TK_RPAREN       	98	/* ) */
#define TK_LISTING      	99	/* listing */
#define TK_CONSULT      	100	/* consult */
#define TK_RECONSULT    	101	/* reconsult */
#define TK_NEQ          	102	/* \= */
#define TK_USER         	103	/* user */
#define TK_BUILTINS     	104	/* builtins */
#define TK_NIL          	105	/* [] */
#define TK_MODULE       	106	/* module */
#define TK_USE          	107	/* use */
#define TK_ENDMOD       	108	/* endmod */
#define TK_EXPORT       	109	/* export */
#define TK_LCURLY       	110	/* { */
#define TK_RCURLY       	111	/* } */
#define TK_CURLYS       	112	/* {} */
#define TK_SQUOTE       	113	/* ' */
#define TK_UNDERSCORE   	114	/* _ */
#define TK_DBREF        	115	/* $dbref */
#define TK_DDOUBLE      	116	/* $double */
#define TK_NOTAGAIN     	117	/* \+ */
#define TK_EXPAND       	118	/* expand */
#define TK_ALSCD        	119	/* als$cd */
#define TK_STREAM_DESCRIPTOR	120	/* stream_descriptor */
#define TK_SYMBOL       	121	/* symbol */
#define TK_QSYMBOL      	122	/* qsymbol */
#define TK_FUNCTOR      	123	/* functor */
#define TK_STRING       	124	/* string */
#define TK_LONG_STRING  	125	/* long_string */
#define TK_LONG_SYMBOL  	126	/* long_symbol */
#define TK_LONG_QSYMBOL 	127	/* long_qsymbol */
#define TK_VAR          	128	/* var */
#define TK_INTEGER      	129	/* integer */
#define TK_UINTEGER     	130	/* uinteger */
#define TK_FULLSTOP     	131	/* fullstop */
#define TK_LEXERR       	132	/* lexerr */
#define TK_COMMENT      	133	/* comment */
#define TK_BYTE         	134	/* byte */
#define TK_UBYTE        	135	/* ubyte */
#define TK_CHAR         	136	/* char */
#define TK_UCHAR        	137	/* uchar */
#define TK_SHORT        	138	/* short */
#define TK_USHORT       	139	/* ushort */
#define TK_RSHORT       	140	/* rshort */
#define TK_RUSHORT      	141	/* rushort */
#define TK_INT          	142	/* int */
#define TK_UINT         	143	/* uint */
#define TK_LONG         	144	/* long */
#define TK_ULONG        	145	/* ulong */
#define TK_FLOAT        	146	/* float */
#define TK_DOUBLE       	147	/* double */
#define TK_FAR          	148	/* dosfar */
#define TK_PREPROC      	149	/* preproc */
#define TK_POUND        	150	/* # */
#define TK_EOLN         	151	/* eoln */
#define TK_LINEINFO     	152	/* lineinfo */
#define TK_ATOM_LENGTH  	153	/* atom_length */
#define TK_ATOM         	154	/* atom */
#define TK_BODY         	155	/* body */
#define TK_CALLABLE     	156	/* callable */
#define TK_CHARACTER    	157	/* character */
#define TK_COMPOUND     	158	/* compound */
#define TK_CONSTANT     	159	/* constant */
#define TK_LIST         	160	/* list */
#define TK_NUMBER       	161	/* number */
#define TK_VARIABLE     	162	/* variable */
#define TK_CHARACTER_CODE_LIST	163	/* character_code_list */
#define TK_CHARACTER_LIST	164	/* character_list */
#define TK_CLOSE_OPTION 	165	/* close_option */
#define TK_FLAG_VALUE   	166	/* flag_value */
#define TK_IO_MODE      	167	/* IO_MODE */
#define TK_NOT_LESS_THAN_ZERO	168	/* not_less_than_zero */
#define TK_OPERATOR_PRIORITY	169	/* operator_priority */
#define TK_OPERATOR_SPECIFIER	170	/* operator_specifier */
#define TK_PROLOG_FLAG  	171	/* prolog_flag */
#define TK_READ_OPTION  	172	/* read_option */
#define TK_SOURCE_SINK  	173	/* source_sink */
#define TK_STREAM_OR_ALIAS	174	/* stream_or_alias */
#define TK_STREAM_OPTION	175	/* stream_option */
#define TK_STREAM_POSITION	176	/* stream_position */
#define TK_WRITE_OPTION 	177	/* write_option */
#define TK_OPERATOR     	178	/* operator */
#define TK_PAST_END_OF_STREAM	179	/* past_end_of_stream */
#define TK_PROCEDURE    	180	/* procedure */
#define TK_STATIC_PROCEDURE	181	/* static_procedure */
#define TK_STREAM       	182	/* stream */
#define TK_ACCESS_CLAUSE	183	/* access_clause */
#define TK_CREATE       	184	/* create */
#define TK_INPUT        	185	/* input */
#define TK_MODIFY       	186	/* modify */
#define TK_OPEN         	187	/* open */
#define TK_OUTPUT       	188	/* output */
#define TK_REPOSITION   	189	/* reposition */
#define TK_CHARACTER_CODE	190	/* character_code */
#define TK_EXCEEDED_MAX_ARITY	191	/* exceeded_max_arity */
#define TK_FLAG         	192	/* flag */
#define TK_DELAY        	193	/* $delay */
#define TK_CMBVARS      	194	/* $combine_dvars */
#define TK_OVERFLOW     	195	/* overflow */
#define TK_UNDERFLOW    	196	/* underflow */
#define TK_ZERO_DIVIDE  	197	/* zero_divide */
#define TK_UNDEFINED    	198	/* undefined */
#define TK_ERROR        	199	/* error */
#define TK_INSTANTIATION_ERROR	200	/* instantiation_error */
#define TK_TYPE_ERROR   	201	/* type_error */
#define TK_DOMAIN_ERROR 	202	/* domain_error */
#define TK_EXISTENCE_ERROR	203	/* existence_error */
#define TK_PERMISSION_ERROR	204	/* permission_error */
#define TK_REPRESENTATION_ERROR	205	/* representation_error */
#define TK_CALCULATION_ERROR	206	/* calculation_error */
#define TK_RESOURCE_ERROR	207	/* resource_error */
#define TK_SYNTAX_ERROR 	208	/* syntax_error */
#define TK_SYSTEM_ERROR 	209	/* system_error */
#define TK_CHAR_CODE    	210	/* char_code */
#define TK_ATOM_CHARS   	211	/* atom_chars */
#define TK_ATOM_CODES   	212	/* atom_codes */
#define TK_NUMBER_CHARS 	213	/* number_chars */
#define TK_NUMBER_CODES 	214	/* number_codes */
#define TK_SNR          	215	/* stream_not_ready */
#define TK_EOF          	216	/* end_of_file */
