#!/bin/sh

# Check for correct number of arguments
if test $# -lt 1
then
    echo 'Usage: win32_setup source_dir [prefix defines...]' 1>&2
    echo 'Example:' 1>&2
    echo '    win32_setup ../alsp_src' 1>&2
    exit 2
fi

# Extract arguments
source_dir=$1
shift 1
defines=$*

# Check for relative source directory
if echo $source_dir | grep -s '^/'
then
    echo "Invalid source directory ($source_dir)" 1>&2
    echo "Source directory must be relative" 1>&2
    exit 2
fi

# Build the prefix file
echo "$defines" > prefix.h

cp $source_dir/win32/alspro_lib.prj.sit.hqx .
cp $source_dir/win32/alspro_dll.prj.sit.hqx .
cp $source_dir/win32/alspro_b.prj.sit.hqx .
cp $source_dir/win32/testdll.x86.prj.sit.hqx .

rm -f package.bat
ln -s $source_dir/win32/package.bat .
rm -f testrun.bat
ln -s $source_dir/win32/testrun.bat .

mkdir alsdir
mkdir alsdir/builtins
rm -f alsdir/builtins/*.pro
ln -s ../../$source_dir/builtins/*.pro alsdir/builtins
mkdir alsdir/library
rm -f alsdir/library/*.pro
ln -s ../../$source_dir/library/*.pro alsdir/library
rm -f alsdir/library/*.alb
ln -s ../../$source_dir/library/*.alb alsdir/library
