const unsigned short sio_chtb[256] = {
/* 00 nul */
SIOC_WHITESPACE,
/* 01 soh  */
SIOC_WHITESPACE,
/* 02 stx */
SIOC_WHITESPACE,
/* 03 etx  */
SIOC_WHITESPACE,
/* 04 eot */
SIOC_WHITESPACE,
/* 05 enq  */
SIOC_WHITESPACE,
/* 06 ack */
SIOC_WHITESPACE,
/* 07 bel */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 08 bs  */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 09 ht   */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 0a nl  */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 0b vt   */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 0c np  */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 0d cr   */
SIOC_WHITESPACE | SIOC_ESCCHAR,
/* 0e so  */
SIOC_WHITESPACE,
/* 0f si  */
SIOC_WHITESPACE,
/* 10 dle */
SIOC_WHITESPACE,
/* 11 dc1  */
SIOC_WHITESPACE,
/* 12 dc2 */
SIOC_WHITESPACE,
/* 13 dc3  */
SIOC_WHITESPACE,
/* 14 dc4 */
SIOC_WHITESPACE,
/* 15 nak  */
SIOC_WHITESPACE,
/* 16 syn */
SIOC_WHITESPACE,
/* 17 etb */
SIOC_WHITESPACE,
/* 18 can */
SIOC_WHITESPACE,
/* 19 em   */
SIOC_WHITESPACE,
/* 1a sub */
SIOC_WHITESPACE,
/* 1b esc  */
SIOC_WHITESPACE,
/* 1c fs  */
SIOC_WHITESPACE,
/* 1d gs   */
SIOC_WHITESPACE,
/* 1e rs  */
SIOC_WHITESPACE,
/* 1f us  */
SIOC_WHITESPACE,
/* 20 sp  */
SIOC_WHITESPACE,
/* 21 !    */
SIOC_SINGLE,
/* 22 "   */
SIOC_SPECIAL,
/* 23 #    */
SIOC_GRAPHIC,
/* 24 $   */
SIOC_GRAPHIC,
/* 25 %    */
SIOC_SPECIAL,
/* 26 &   */
SIOC_GRAPHIC,
/* 27 '   */
SIOC_SPECIAL | SIOC_ESCCHAR,
/* 28 (   */
SIOC_SINGLE,
/* 29 )    */
SIOC_SINGLE,
/* 2a *   */
SIOC_GRAPHIC,
/* 2b +    */
SIOC_GRAPHIC | SIOC_PLUSMINUS,
/* 2c ,   */
SIOC_SINGLE,
/* 2d -    */
SIOC_GRAPHIC | SIOC_PLUSMINUS,
/* 2e .   */
SIOC_GRAPHIC,
/* 2f /   */
SIOC_GRAPHIC,
/* 30 0   */
SIOC_DECIMAL | SIOC_OCTAL,
/* 31 1    */
SIOC_DECIMAL | SIOC_OCTAL,
/* 32 2   */
SIOC_DECIMAL | SIOC_OCTAL,
/* 33 3    */
SIOC_DECIMAL | SIOC_OCTAL,
/* 34 4   */
SIOC_DECIMAL | SIOC_OCTAL,
/* 35 5    */
SIOC_DECIMAL | SIOC_OCTAL,
/* 36 6   */
SIOC_DECIMAL | SIOC_OCTAL,
/* 37 7   */
SIOC_DECIMAL | SIOC_OCTAL,
/* 38 8   */
SIOC_DECIMAL,
/* 39 9    */
SIOC_DECIMAL,
/* 3a :   */
SIOC_GRAPHIC,
/* 3b ;    */
SIOC_SINGLE,
/* 3c <   */
SIOC_GRAPHIC,
/* 3d =    */
SIOC_GRAPHIC,
/* 3e >   */
SIOC_GRAPHIC,
/* 3f ?   */
SIOC_GRAPHIC,
/* 40 @   */
SIOC_GRAPHIC,
/* 41 A    */
SIOC_UPPERCASE | SIOC_HEXUPPER,
/* 42 B   */
SIOC_UPPERCASE | SIOC_HEXUPPER,
/* 43 C    */
SIOC_UPPERCASE | SIOC_HEXUPPER,
/* 44 D   */
SIOC_UPPERCASE | SIOC_HEXUPPER,
/* 45 E    */
SIOC_UPPERCASE | SIOC_HEXUPPER | SIOC_E,
/* 46 F   */
SIOC_UPPERCASE | SIOC_HEXUPPER,
/* 47 G   */
SIOC_UPPERCASE,
/* 48 H   */
SIOC_UPPERCASE,
/* 49 I    */
SIOC_UPPERCASE,
/* 4a J   */
SIOC_UPPERCASE,
/* 4b K    */
SIOC_UPPERCASE,
/* 4c L   */
SIOC_UPPERCASE,
/* 4d M    */
SIOC_UPPERCASE,
/* 4e N   */
SIOC_UPPERCASE,
/* 4f O   */
SIOC_UPPERCASE,
/* 50 P   */
SIOC_UPPERCASE,
/* 51 Q    */
SIOC_UPPERCASE,
/* 52 R   */
SIOC_UPPERCASE,
/* 53 S    */
SIOC_UPPERCASE,
/* 54 T   */
SIOC_UPPERCASE,
/* 55 U    */
SIOC_UPPERCASE,
/* 56 V   */
SIOC_UPPERCASE,
/* 57 W   */
SIOC_UPPERCASE,
/* 58 X   */
SIOC_UPPERCASE,
/* 59 Y    */
SIOC_UPPERCASE,
/* 5a Z   */
SIOC_UPPERCASE,
/* 5b [    */
SIOC_SINGLE,
/* 5c \   */
SIOC_GRAPHIC | SIOC_ESCCHAR,
/* 5d ]    */
SIOC_SINGLE,
/* 5e ^   */
SIOC_GRAPHIC,
/* 5f _   */
SIOC_UPPERCASE,
/* 60 `   */
SIOC_GRAPHIC,
/* 61 a    */
SIOC_LOWERCASE | SIOC_HEXLOWER,
/* 62 b   */
SIOC_LOWERCASE | SIOC_HEXLOWER,
/* 63 c    */
SIOC_LOWERCASE | SIOC_HEXLOWER,
/* 64 d   */
SIOC_LOWERCASE | SIOC_HEXLOWER,
/* 65 e    */
SIOC_LOWERCASE | SIOC_HEXLOWER | SIOC_E,
/* 66 f   */
SIOC_LOWERCASE | SIOC_HEXLOWER,
/* 67 g   */
SIOC_LOWERCASE,
/* 68 h   */
SIOC_LOWERCASE,
/* 69 i    */
SIOC_LOWERCASE,
/* 6a j   */
SIOC_LOWERCASE,
/* 6b k    */
SIOC_LOWERCASE,
/* 6c l   */
SIOC_LOWERCASE,
/* 6d m    */
SIOC_LOWERCASE,
/* 6e n   */
SIOC_LOWERCASE,
/* 6f o   */
SIOC_LOWERCASE,
/* 70 p   */
SIOC_LOWERCASE,
/* 71 q    */
SIOC_LOWERCASE,
/* 72 r   */
SIOC_LOWERCASE,
/* 73 s    */
SIOC_LOWERCASE,
/* 74 t   */
SIOC_LOWERCASE,
/* 75 u    */
SIOC_LOWERCASE,
/* 76 v   */
SIOC_LOWERCASE,
/* 77 w   */
SIOC_LOWERCASE,
/* 78 x   */
SIOC_LOWERCASE,
/* 79 y    */
SIOC_LOWERCASE,
/* 7a z   */
SIOC_LOWERCASE,
/* 7b {    */
SIOC_SINGLE,
/* 7c | */
SIOC_SINGLE,
/* 7d }    */
SIOC_SINGLE,
/* 7e ~   */
SIOC_GRAPHIC,
/* 7f del */
SIOC_WHITESPACE,

SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE,
SIOC_LOWERCASE
};
