SOURCE_DIR=../../alsp_src
OS=unix
SUBOS=darwin
PROC=port

# Include Tcl/Tk headers on system path for alsdev
BUILD_FLAGS=-isystem /usr/local/include/tcl-tk
TCLVER=8.6
include $(SOURCE_DIR)/generic/gnu_makefile
