SOURCE_DIR=../../alsp_src
OS=unix
SUBOS=darwin
PROC=port
SDK=$(shell xcrun --show-sdk-path)
BUILD_FLAGS=-I$(SDK)/System/Library/Frameworks/Tk.framework/Versions/Current/Headers
include $(SOURCE_DIR)/generic/gnu_makefile
