# Solaris makefile header for ALS Prolog's Tcl interface library 

UNIX_NAME=Solaris

include ../common/unix_makefile

LDFLAGS += -Xlinker -B -Xlinker symbolic -Xlinker -s -Xlinker -R. -Xlinker -R/usr/local/lib/ -L /usr/openwin/lib
