# Solaris makefile header for ALS Prolog's Tcl interface library 

LINK = -shared -Xlinker -B -Xlinker symbolic -Xlinker -s -Xlinker -R. -Xlinker -R/usr/local/lib/ -L /usr/openwin/lib
UNIX_NAME=Solaris

include ../common/unix_makefile
