# Irix makefile header for ALS Prolog's Tcl interface library 

SUBOS_INCLUDE = -isystem /misc/ken-working/include
LINK = -shared -L/misc/ken-working/lib
UNIX_NAME=Irix

include ../common/unix_makefile
