# Irix makefile header for ALS Prolog's Tcl interface library 

SUBOS_INCLUDE = -isystem /misc/ken-working/tcltk/tcl8.0/generic -isystem /misc/ken-working/tcltk/tk8.0/generic
LINK = -shared -L/misc/ken-working/tcltk/tcl8.0/unix -L/misc/ken-working/tcltk/tk8.0/unix 
UNIX_NAME=Irix

include ../common/unix_makefile
