#!/bin/sh

mac=$1
unix=$2
win=$3
vers=3.1

mkhybrid -hfs --netatalk -r -J \
	-hide-hfs "$unix/*" -hide-hfs "$win/*" \
	-hide "$mac/*" -hide "$win/*" \
	-hide-joliet "$mac/*" -hide-joliet "$unix/*" \
	-P "Applied Logic Systems, Inc. http://www.als.com" \
	-p "Applied Logic Systems, Inc. http://www.als.com" \
	-A "ALS Student Prolog $vers" \
	-V "ALS Student Prolog $vers" \
	-o als-student-prolog-$vers-cd.image "$mac" "$unix" "$win"	



