#!/bin/sh

mac=$1
unix=$2
wins=$3
vers=3.1
edition=$4

case $edition in
student)
VOLNAME="ALS Student Prolog $vers"
OUTPUT="als-student-prolog-$vers-cd.image"
;;
standard)
VOLNAME="ALS Prolog $vers"
OUTPUT="als-prolog-$vers-cd.image"
;;
esac

mkhybrid -hfs --netatalk -r -J \
	-hide-hfs "$unix/*" -hide-hfs "$wins/*" \
	-hide "$mac/*" -hide "$wins/*" \
	-hide-joliet "$mac/*" -hide-joliet "$unix/*" \
	-P "Applied Logic Systems, Inc. http://www.als.com" \
	-p "Applied Logic Systems, Inc. http://www.als.com" \
	-A $VOLNAME \
	-V $VOLNAME \
	-o $OUTPUT "$mac" "$unix" "$wins"	



