wm_fail_builtin(){}
wm_nciadc(){}
#ifdef notdef
wm_try(){}
wm_trust(){}
wm_sw_const(){}
wm_sw_struct(){}
wm_compare(){}
wm_retry(){}
wm_atom(){}
wm_arg(){}
wm_g_int(){}
wm_arrow(){}
wm_retry_me(){}
wm_execute_builtin(){}
wm_exec(){}
wm_atomic(){}
wm_g_sym(){}
wm_trust_fail(){}
wm_resolve_ref(){}
wm_call(){}
wm_functor(){}
wm_eq(){}
wm_g_uia(){}
wm_trust_me(){}
wm_rungoal(){}
wm_colon(){}
wm_try_me(){}
wm_cut(){}
wm_var(){}
wm_nonvar(){}
wm_comma(){}
wm_mangle(){}
wm_float(){}
wm_p_uia(){}
wm_dbg_call(){}
wm_docut(){}
wm_p_unsafe(){}
wm_integer(){}
wm_noneq(){}
wm_unify(){}
wm_jump(){}
wm_ocall(){}
wm_u_int(){}
wm_number(){}
wm_u_lval(){}
wm_semicolon(){}
wm_u_sym(){}
_w_unify(){}
wm_fail(){}
set_prolog_interrupt(){}
wm_throw(){}
wm_abort(){}
wm_catch22(){}
dbg_spycheck(){}
dbg_decr_icount(){}
wm_overflow(){}
wm_nonidentical(){}
wm_identical(){}
#endif
