#!/bin/sh
 
vers=3.1
BUILDSUP="/apache/als_build_support"
  
if test $# -gt 1
then
	echo "$0: Too many args" 1>&2
	echo "Usage: $0 [srcroot]" 1>&2
	exit 2
elif test $# -eq 1
then
	srcroot=$1
else
	srcroot=/apache/adb
fi

if test -d $srcroot
then
	echo Using srcroot = $srcroot
else
	echo Creating srcroot = $srcroot
	mkdir $srcroot
fi
									
case `uname -rs` in \
	"SunOS 4"*)     ARCH=sunos  ;; \
	"SunOS 5"*)     ARCH=solaris    ;; \
	Linux*)     ARCH=linux  ;; \
	"HP-UX"*)   ARCH=hpux   ;; \
	"IRIX"*)    ARCH=irix   ;; \
	*)      echo "Unknown machine type..."; exit 1 ;; \
esac ; 

echo "Using ARCH=$ARCH...vers=$vers"

if test -d $srcroot/$ARCH
then
	echo "$srcroot/$ARCH exists"
else
	echo "Creating $srcroot/$ARCH ..."
	mkdir $srcroot/$ARCH
fi
echo "Setting up distribution in $srcroot/$ARCH"


STANDARD="$srcroot/$ARCH/standard"

rm -rf $srcroot/$ARCH/*
mkdir $STANDARD

cp als-prolog-$ARCH.tgz $STANDARD

cp ../manual/welcome_standard.als/ $STANDARD/Welcome

cp $BUILDSUP/unix/$ARCH/tools/ar*.tar.* $STANDARD

cp $BUILDSUP/unix/$ARCH/tools/gzip $STANDARD

RELEASE="../manual/release_standard_$vers"
if test -f $RELEASE
then
	cp $RELEASE $STANDARD/ReleaseNotes_$vers
else
	echo "No release notes for Version $vers"
fi
