#!/bin/sh
# Create an appropriate build subdirectory
#
echo making directory for system = $1
case $1 in
	hppa) 		setup.dir hppa hpux9.05 unix "-Dhp9" ;;
	powerpc)	setup.dir powerpc aix4.1.1 unix aix4 ;;
	sunos)		setup.dir sparc sunos4.1.3 unix ;;
	solaris)	setup.dir sparc solaris2.4 unix solaris2 ;;
	dj1) 		setup.dir i386 djgpp1 unix djgpp1 '' i386_dj1 ;;
	dj2) 		setup.dir i386 djgpp2 unix djgpp2 '' i386_dj2 ;;
	*)			echo unknown system: $1 ;;
esac
