#!/bin/sh
#
# Copy files of SystemV version of 386 system
#

DESTDIR=/elvis/pcfs/tmp

cd SYSV/obj ; \
	for i in *.[chs] *.m4; do  cp $i $DESTDIR/$i ; done; \
	cp Makefile.sys $DESTDIR/makefile;


cd SYSV/obj/alsdir ; \
	for i in *.pro ; do  cp $i $DESTDIR/$i ; done;


cp SYSV/obj/fromdisk $DESTDIR/fromdisk

topc SYSV/obj/todisk > $DESTDIR/todisk.bat
 
 
 
#
# Let everybody to access files in the destination directory
#
 
chmod 777 $DESTDIR/*
 

