#
# Makefile for the interface to the accsys library
# ---- version for >> sparc_sunos4.1.3 <<
#
ARCH 	= sparc
OS 		= sunos4.1.3
SOS		= sunos4
GOS		= unix
PROTYPE	= port
XINCLUDES	= -I /mailbox3/builds/sparc_sunos4.1.3
 
#all: d3i d3x d3z d3t d3n d3iz d3in d3ix d3inz d3ixz d3it d3int d3ixt d3intz d3ixtz
 
all: d3i d3iz
	echo all done
 
include ../../makefile.cmn
