#define VERSION_STRING "1.0"
#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0

/* 
Win32 File Flag choices:

VS_FF_DEBUG
VS_FF_PRERELEASE
VS_FF_PATCHED
VS_FF_PRIVATEBUILD
VS_FF_INFOINFERRED
VS_FF_SPECIALBUILD
0x0L for final release
*/
#define VERSION_WIN32_FILEFLAGS 0x0L
