#
# Makefile for the interface to the accsys library
# ---- version for >> sparc_solaris2.4 <<
#
ARCH = sparc
OS = solaris2.4
GOS = unix
 
#all: d3i d3x d3z d3t d3n d3iz d3in d3ix d3inz d3ixz d3it d3int d3ixt d3intz d3ixtz
 
all: d3i d3iz
	echo all done
 
include ../makefile.inf
include ../../makefile.cmn
