# Site settings
title: "ALS Prolog"
url: "https://alsprolog.com"

# Build settings
markdown: kramdown
#permalink: pretty

# Enable as many error-checks as possible
safe                : true
strict_front_matter : true
liquid:
  error_mode        : strict
  strict_filters    : true
  strict_variables  : true

defaults:
  -
    scope:
      path: "src_help_md/md_help"
      type: "pages"
    values:
      reference: true
      package: Core Prolog
      group: Control
      layout: "reference-page"
