# Site settings
title: "ALS Prolog"
url: "https://alsprolog.com"

repository: "AppliedLogicSystems/ALSProlog"

# Build settings
markdown: kramdown
theme: minima
#permalink: pretty

kramdown:
  syntax_highlighter_opts:
    default_lang: prolog

# Enable as many error-checks as possible
safe                : true
strict_front_matter : true
liquid:
  error_mode        : strict
  strict_filters    : true
  strict_variables  : false

exclude:
  - src_help_md

header_pages:
 - about.md
 - docs.md

defaults:
  -
    scope:
      path: "ref-manual/alshelp"
      type: "pages"
    values:
      reference: true
      package: Core Prolog
      group: Control
      module: builtins
      layout: "reference-page"
