# Site settings
title: "ALS Prolog"
url: "https://alsprolog.com"

repository: "AppliedLogicSystems/ALSProlog"

# Build settings
markdown: kramdown
theme: minima
#permalink: pretty

kramdown:
  syntax_highlighter_opts:
    default_lang: prolog

# Enable as many error-checks as possible
safe                : true
strict_front_matter : true
liquid:
  error_mode        : strict
  strict_filters    : true
  strict_variables  : false

exclude:
  - src_help_md

header_pages:
  - docs/index.md
  - about.md

ref_packages:
  - Core Prolog
  - alslib
  - C Interface
  - ALSDev

defaults:
  -
    scope:
      path: "docs/ref"
      type: "pages"
    values:
      reference: true
      package: Core Prolog
      group: Control
      module: builtins
      layout: "reference-page"
  -
    scope:
      path: "docs/guide"
      type: "pages"
    values:
      layout: "guide-page"
