/*================================================================

          odbc2.c

          --Generated from: odbc.src

          Date: 96/4/25   Time: 14:41:55

		--by ALS Interface Generator



 *===============================================================*/



#include "alspi.h"

#include "cinterf.h"

#include "odbc.h"





void odbc3_init(void)

{

  CI_INTCONST("ODBCVER",ODBCVER)

  CI_INTCONST("SQL_SPEC_MAJOR",SQL_SPEC_MAJOR)

  CI_INTCONST("SQL_SPEC_MINOR",SQL_SPEC_MINOR)

  CI_STRINGCONST("SQL_SPEC_STRING",SQL_SPEC_STRING)

  CI_INTCONST("SQL_SQLSTATE_SIZE",SQL_SQLSTATE_SIZE)

  CI_INTCONST("SQL_MAX_MESSAGE_LENGTH",SQL_MAX_MESSAGE_LENGTH)

  CI_INTCONST("SQL_MAX_DSN_LENGTH",SQL_MAX_DSN_LENGTH)

  CI_INTCONST("SQL_INVALID_HANDLE",SQL_INVALID_HANDLE)

  CI_INTCONST("SQL_ERROR",SQL_ERROR)

  CI_INTCONST("SQL_SUCCESS",SQL_SUCCESS)

  CI_INTCONST("SQL_SUCCESS_WITH_INFO",SQL_SUCCESS_WITH_INFO)

  CI_INTCONST("SQL_NO_DATA_FOUND",SQL_NO_DATA_FOUND)

  CI_INTCONST("SQL_CHAR",SQL_CHAR)

  CI_INTCONST("SQL_NUMERIC",SQL_NUMERIC)

  CI_INTCONST("SQL_DECIMAL",SQL_DECIMAL)

  CI_INTCONST("SQL_INTEGER",SQL_INTEGER)

  CI_INTCONST("SQL_SMALLINT",SQL_SMALLINT)

  CI_INTCONST("SQL_FLOAT",SQL_FLOAT)

  CI_INTCONST("SQL_REAL",SQL_REAL)

  CI_INTCONST("SQL_DOUBLE",SQL_DOUBLE)

  CI_INTCONST("SQL_VARCHAR",SQL_VARCHAR)

  CI_INTCONST("SQL_TYPE_MIN",SQL_TYPE_MIN)

  CI_INTCONST("SQL_TYPE_NULL",SQL_TYPE_NULL)

  CI_INTCONST("SQL_TYPE_MAX",SQL_TYPE_MAX)

  CI_INTCONST("SQL_C_CHAR",SQL_C_CHAR)

  CI_INTCONST("SQL_C_LONG",SQL_C_LONG)

  CI_INTCONST("SQL_C_SHORT",SQL_C_SHORT)

  CI_INTCONST("SQL_C_FLOAT",SQL_C_FLOAT)

  CI_INTCONST("SQL_C_DOUBLE",SQL_C_DOUBLE)

  CI_INTCONST("SQL_C_DEFAULT",SQL_C_DEFAULT)

  CI_INTCONST("SQL_NO_NULLS",SQL_NO_NULLS)

  CI_INTCONST("SQL_NULLABLE",SQL_NULLABLE)

  CI_INTCONST("SQL_NULLABLE_UNKNOWN",SQL_NULLABLE_UNKNOWN)

  CI_INTCONST("SQL_NULL_DATA",SQL_NULL_DATA)

  CI_INTCONST("SQL_DATA_AT_EXEC",SQL_DATA_AT_EXEC)

  CI_INTCONST("SQL_NTS",SQL_NTS)

  CI_INTCONST("SQL_CLOSE",SQL_CLOSE)

  CI_INTCONST("SQL_DROP",SQL_DROP)

  CI_INTCONST("SQL_UNBIND",SQL_UNBIND)

  CI_INTCONST("SQL_RESET_PARAMS",SQL_RESET_PARAMS)

  CI_INTCONST("SQL_COMMIT",SQL_COMMIT)

  CI_INTCONST("SQL_ROLLBACK",SQL_ROLLBACK)

  CI_INTCONST("SQL_COLUMN_COUNT",SQL_COLUMN_COUNT)

  CI_INTCONST("SQL_COLUMN_NAME",SQL_COLUMN_NAME)

  CI_INTCONST("SQL_COLUMN_TYPE",SQL_COLUMN_TYPE)

  CI_INTCONST("SQL_COLUMN_LENGTH",SQL_COLUMN_LENGTH)

  CI_INTCONST("SQL_COLUMN_PRECISION",SQL_COLUMN_PRECISION)

  CI_INTCONST("SQL_COLUMN_SCALE",SQL_COLUMN_SCALE)

  CI_INTCONST("SQL_COLUMN_DISPLAY_SIZE",SQL_COLUMN_DISPLAY_SIZE)

  CI_INTCONST("SQL_COLUMN_NULLABLE",SQL_COLUMN_NULLABLE)

  CI_INTCONST("SQL_COLUMN_UNSIGNED",SQL_COLUMN_UNSIGNED)

  CI_INTCONST("SQL_COLUMN_MONEY",SQL_COLUMN_MONEY)

  CI_INTCONST("SQL_COLUMN_UPDATABLE",SQL_COLUMN_UPDATABLE)

  CI_INTCONST("SQL_COLUMN_AUTO_INCREMENT",SQL_COLUMN_AUTO_INCREMENT)

  CI_INTCONST("SQL_COLUMN_CASE_SENSITIVE",SQL_COLUMN_CASE_SENSITIVE)

  CI_INTCONST("SQL_COLUMN_SEARCHABLE",SQL_COLUMN_SEARCHABLE)

  CI_INTCONST("SQL_COLUMN_TYPE_NAME",SQL_COLUMN_TYPE_NAME)

  CI_INTCONST("SQL_COLUMN_TABLE_NAME",SQL_COLUMN_TABLE_NAME)

  CI_INTCONST("SQL_COLUMN_OWNER_NAME",SQL_COLUMN_OWNER_NAME)

  CI_INTCONST("SQL_COLUMN_QUALIFIER_NAME",SQL_COLUMN_QUALIFIER_NAME)

  CI_INTCONST("SQL_COLUMN_LABEL",SQL_COLUMN_LABEL)

  CI_INTCONST("SQL_COLATT_OPT_MAX",SQL_COLATT_OPT_MAX)

  CI_INTCONST("SQL_COLUMN_DRIVER_START",SQL_COLUMN_DRIVER_START)

  CI_INTCONST("SQL_COLATT_OPT_MIN",SQL_COLATT_OPT_MIN)

  CI_INTCONST("SQL_ATTR_READONLY",SQL_ATTR_READONLY)

  CI_INTCONST("SQL_ATTR_WRITE",SQL_ATTR_WRITE)

  CI_INTCONST("SQL_ATTR_READWRITE_UNKNOWN",SQL_ATTR_READWRITE_UNKNOWN)

  CI_INTCONST("SQL_UNSEARCHABLE",SQL_UNSEARCHABLE)

  CI_INTCONST("SQL_LIKE_ONLY",SQL_LIKE_ONLY)

  CI_INTCONST("SQL_ALL_EXCEPT_LIKE",SQL_ALL_EXCEPT_LIKE)

  CI_INTCONST("SQL_SEARCHABLE",SQL_SEARCHABLE)

  CI_INTCONST("SQL_NULL_HENV",SQL_NULL_HENV)

  CI_INTCONST("SQL_NULL_HDBC",SQL_NULL_HDBC)

  CI_INTCONST("SQL_NULL_HSTMT",SQL_NULL_HSTMT)

  CI_INTCONST("SQL_MAX_OPTION_STRING_LENGTH",SQL_MAX_OPTION_STRING_LENGTH)

  CI_INTCONST("SQL_STILL_EXECUTING",SQL_STILL_EXECUTING)

  CI_INTCONST("SQL_NEED_DATA",SQL_NEED_DATA)

  CI_INTCONST("SQL_DATE",SQL_DATE)

  CI_INTCONST("SQL_TIME",SQL_TIME)

  CI_INTCONST("SQL_TIMESTAMP",SQL_TIMESTAMP)

  CI_INTCONST("SQL_LONGVARCHAR",SQL_LONGVARCHAR)

  CI_INTCONST("SQL_BINARY",SQL_BINARY)

  CI_INTCONST("SQL_VARBINARY",SQL_VARBINARY)

  CI_INTCONST("SQL_LONGVARBINARY",SQL_LONGVARBINARY)

  CI_INTCONST("SQL_BIGINT",SQL_BIGINT)

  CI_INTCONST("SQL_TINYINT",SQL_TINYINT)

  CI_INTCONST("SQL_BIT",SQL_BIT)

  CI_INTCONST("SQL_INTERVAL_YEAR",SQL_INTERVAL_YEAR)

  CI_INTCONST("SQL_INTERVAL_MONTH",SQL_INTERVAL_MONTH)

  CI_INTCONST("SQL_INTERVAL_YEAR_TO_MONTH",SQL_INTERVAL_YEAR_TO_MONTH)

  CI_INTCONST("SQL_INTERVAL_DAY",SQL_INTERVAL_DAY)

  CI_INTCONST("SQL_INTERVAL_HOUR",SQL_INTERVAL_HOUR)

  CI_INTCONST("SQL_INTERVAL_MINUTE",SQL_INTERVAL_MINUTE)

  CI_INTCONST("SQL_INTERVAL_SECOND",SQL_INTERVAL_SECOND)

  CI_INTCONST("SQL_INTERVAL_DAY_TO_HOUR",SQL_INTERVAL_DAY_TO_HOUR)

  CI_INTCONST("SQL_INTERVAL_DAY_TO_MINUTE",SQL_INTERVAL_DAY_TO_MINUTE)

  CI_INTCONST("SQL_INTERVAL_DAY_TO_SECOND",SQL_INTERVAL_DAY_TO_SECOND)

  CI_INTCONST("SQL_INTERVAL_HOUR_TO_MINUTE",SQL_INTERVAL_HOUR_TO_MINUTE)

  CI_INTCONST("SQL_INTERVAL_HOUR_TO_SECOND",SQL_INTERVAL_HOUR_TO_SECOND)

  CI_INTCONST("SQL_INTERVAL_MINUTE_TO_SECOND",SQL_INTERVAL_MINUTE_TO_SECOND)

  CI_INTCONST("SQL_UNICODE",SQL_UNICODE)

  CI_INTCONST("SQL_TYPE_DRIVER_START",SQL_TYPE_DRIVER_START)

  CI_INTCONST("SQL_TYPE_DRIVER_END",SQL_TYPE_DRIVER_END)

  CI_INTCONST("SQL_SIGNED_OFFSET",SQL_SIGNED_OFFSET)

  CI_INTCONST("SQL_UNSIGNED_OFFSET",SQL_UNSIGNED_OFFSET)

  CI_INTCONST("SQL_C_DATE",SQL_C_DATE)

  CI_INTCONST("SQL_C_TIME",SQL_C_TIME)

  CI_INTCONST("SQL_C_TIMESTAMP",SQL_C_TIMESTAMP)

  CI_INTCONST("SQL_C_BINARY",SQL_C_BINARY)

  CI_INTCONST("SQL_C_BIT",SQL_C_BIT)

  CI_INTCONST("SQL_C_TINYINT",SQL_C_TINYINT)

  CI_INTCONST("SQL_C_SLONG",SQL_C_SLONG)

  CI_INTCONST("SQL_C_SSHORT",SQL_C_SSHORT)

  CI_INTCONST("SQL_C_STINYINT",SQL_C_STINYINT)

  CI_INTCONST("SQL_C_ULONG",SQL_C_ULONG)

  CI_INTCONST("SQL_C_USHORT",SQL_C_USHORT)

  CI_INTCONST("SQL_C_UTINYINT",SQL_C_UTINYINT)

  CI_INTCONST("SQL_C_BOOKMARK",SQL_C_BOOKMARK)

  CI_INTCONST("SQL_ALL_TYPES",SQL_ALL_TYPES)

  CI_INTCONST("SQL_DRIVER_NOPROMPT",SQL_DRIVER_NOPROMPT)

  CI_INTCONST("SQL_DRIVER_COMPLETE",SQL_DRIVER_COMPLETE)

  CI_INTCONST("SQL_DRIVER_PROMPT",SQL_DRIVER_PROMPT)

  CI_INTCONST("SQL_DRIVER_COMPLETE_REQUIRED",SQL_DRIVER_COMPLETE_REQUIRED)

  CI_INTCONST("SQL_NO_TOTAL",SQL_NO_TOTAL)

  CI_INTCONST("SQL_DEFAULT_PARAM",SQL_DEFAULT_PARAM)

  CI_INTCONST("SQL_IGNORE",SQL_IGNORE)

  CI_INTCONST("SQL_LEN_DATA_AT_EXEC_OFFSET",SQL_LEN_DATA_AT_EXEC_OFFSET)

  CI_INTCONST("SQL_API_SQLALLOCCONNECT",SQL_API_SQLALLOCCONNECT)

  CI_INTCONST("SQL_API_SQLALLOCENV",SQL_API_SQLALLOCENV)

  CI_INTCONST("SQL_API_SQLALLOCSTMT",SQL_API_SQLALLOCSTMT)

  CI_INTCONST("SQL_API_SQLBINDCOL",SQL_API_SQLBINDCOL)

  CI_INTCONST("SQL_API_SQLCANCEL",SQL_API_SQLCANCEL)

  CI_INTCONST("SQL_API_SQLCOLATTRIBUTES",SQL_API_SQLCOLATTRIBUTES)

  CI_INTCONST("SQL_API_SQLCONNECT",SQL_API_SQLCONNECT)

  CI_INTCONST("SQL_API_SQLDESCRIBECOL",SQL_API_SQLDESCRIBECOL)

  CI_INTCONST("SQL_API_SQLDISCONNECT",SQL_API_SQLDISCONNECT)

  CI_INTCONST("SQL_API_SQLERROR",SQL_API_SQLERROR)

  CI_INTCONST("SQL_API_SQLEXECDIRECT",SQL_API_SQLEXECDIRECT)

  CI_INTCONST("SQL_API_SQLEXECUTE",SQL_API_SQLEXECUTE)

  CI_INTCONST("SQL_API_SQLFETCH",SQL_API_SQLFETCH)

  CI_INTCONST("SQL_API_SQLFREECONNECT",SQL_API_SQLFREECONNECT)

  CI_INTCONST("SQL_API_SQLFREEENV",SQL_API_SQLFREEENV)

  CI_INTCONST("SQL_API_SQLFREESTMT",SQL_API_SQLFREESTMT)

  CI_INTCONST("SQL_API_SQLGETCURSORNAME",SQL_API_SQLGETCURSORNAME)

  CI_INTCONST("SQL_API_SQLNUMRESULTCOLS",SQL_API_SQLNUMRESULTCOLS)

  CI_INTCONST("SQL_API_SQLPREPARE",SQL_API_SQLPREPARE)

  CI_INTCONST("SQL_API_SQLROWCOUNT",SQL_API_SQLROWCOUNT)

  CI_INTCONST("SQL_API_SQLSETCURSORNAME",SQL_API_SQLSETCURSORNAME)

  CI_INTCONST("SQL_API_SQLSETPARAM",SQL_API_SQLSETPARAM)

  CI_INTCONST("SQL_API_SQLTRANSACT",SQL_API_SQLTRANSACT)

  CI_INTCONST("SQL_NUM_FUNCTIONS",SQL_NUM_FUNCTIONS)

  CI_INTCONST("SQL_EXT_API_START",SQL_EXT_API_START)

  CI_INTCONST("SQL_API_SQLCOLUMNS",SQL_API_SQLCOLUMNS)

  CI_INTCONST("SQL_API_SQLDRIVERCONNECT",SQL_API_SQLDRIVERCONNECT)

  CI_INTCONST("SQL_API_SQLGETCONNECTOPTION",SQL_API_SQLGETCONNECTOPTION)

  CI_INTCONST("SQL_API_SQLGETDATA",SQL_API_SQLGETDATA)

  CI_INTCONST("SQL_API_SQLGETFUNCTIONS",SQL_API_SQLGETFUNCTIONS)

  CI_INTCONST("SQL_API_SQLGETINFO",SQL_API_SQLGETINFO)

  CI_INTCONST("SQL_API_SQLGETSTMTOPTION",SQL_API_SQLGETSTMTOPTION)

  CI_INTCONST("SQL_API_SQLGETTYPEINFO",SQL_API_SQLGETTYPEINFO)

  CI_INTCONST("SQL_API_SQLPARAMDATA",SQL_API_SQLPARAMDATA)

  CI_INTCONST("SQL_API_SQLPUTDATA",SQL_API_SQLPUTDATA)

  CI_INTCONST("SQL_API_SQLSETCONNECTOPTION",SQL_API_SQLSETCONNECTOPTION)

  CI_INTCONST("SQL_API_SQLSETSTMTOPTION",SQL_API_SQLSETSTMTOPTION)

  CI_INTCONST("SQL_API_SQLSPECIALCOLUMNS",SQL_API_SQLSPECIALCOLUMNS)

  CI_INTCONST("SQL_API_SQLSTATISTICS",SQL_API_SQLSTATISTICS)

  CI_INTCONST("SQL_API_SQLTABLES",SQL_API_SQLTABLES)

  CI_INTCONST("SQL_API_SQLBROWSECONNECT",SQL_API_SQLBROWSECONNECT)

  CI_INTCONST("SQL_API_SQLCOLUMNPRIVILEGES",SQL_API_SQLCOLUMNPRIVILEGES)

  CI_INTCONST("SQL_API_SQLDATASOURCES",SQL_API_SQLDATASOURCES)

  CI_INTCONST("SQL_API_SQLDESCRIBEPARAM",SQL_API_SQLDESCRIBEPARAM)

  CI_INTCONST("SQL_API_SQLEXTENDEDFETCH",SQL_API_SQLEXTENDEDFETCH)

  CI_INTCONST("SQL_API_SQLFOREIGNKEYS",SQL_API_SQLFOREIGNKEYS)

  CI_INTCONST("SQL_API_SQLMORERESULTS",SQL_API_SQLMORERESULTS)

  CI_INTCONST("SQL_API_SQLNATIVESQL",SQL_API_SQLNATIVESQL)

  CI_INTCONST("SQL_API_SQLNUMPARAMS",SQL_API_SQLNUMPARAMS)

  CI_INTCONST("SQL_API_SQLPARAMOPTIONS",SQL_API_SQLPARAMOPTIONS)

  CI_INTCONST("SQL_API_SQLPRIMARYKEYS",SQL_API_SQLPRIMARYKEYS)

  CI_INTCONST("SQL_API_SQLPROCEDURECOLUMNS",SQL_API_SQLPROCEDURECOLUMNS)

  CI_INTCONST("SQL_API_SQLPROCEDURES",SQL_API_SQLPROCEDURES)

  CI_INTCONST("SQL_API_SQLSETPOS",SQL_API_SQLSETPOS)

  CI_INTCONST("SQL_API_SQLSETSCROLLOPTIONS",SQL_API_SQLSETSCROLLOPTIONS)

  CI_INTCONST("SQL_API_SQLTABLEPRIVILEGES",SQL_API_SQLTABLEPRIVILEGES)

  CI_INTCONST("SQL_API_SQLDRIVERS",SQL_API_SQLDRIVERS)

  CI_INTCONST("SQL_API_SQLBINDPARAMETER",SQL_API_SQLBINDPARAMETER)

  CI_INTCONST("SQL_EXT_API_LAST",SQL_EXT_API_LAST)

  CI_INTCONST("SQL_API_ALL_FUNCTIONS",SQL_API_ALL_FUNCTIONS)

  CI_INTCONST("SQL_NUM_EXTENSIONS",SQL_NUM_EXTENSIONS)

  CI_INTCONST("SQL_API_LOADBYORDINAL",SQL_API_LOADBYORDINAL)

  CI_INTCONST("SQL_INFO_FIRST",SQL_INFO_FIRST)

  CI_INTCONST("SQL_ACTIVE_CONNECTIONS",SQL_ACTIVE_CONNECTIONS)

  CI_INTCONST("SQL_ACTIVE_STATEMENTS",SQL_ACTIVE_STATEMENTS)

  CI_INTCONST("SQL_DATA_SOURCE_NAME",SQL_DATA_SOURCE_NAME)

  CI_INTCONST("SQL_DRIVER_HDBC",SQL_DRIVER_HDBC)

  CI_INTCONST("SQL_DRIVER_HENV",SQL_DRIVER_HENV)

  CI_INTCONST("SQL_DRIVER_HSTMT",SQL_DRIVER_HSTMT)

  CI_INTCONST("SQL_DRIVER_NAME",SQL_DRIVER_NAME)

  CI_INTCONST("SQL_DRIVER_VER",SQL_DRIVER_VER)

  CI_INTCONST("SQL_FETCH_DIRECTION",SQL_FETCH_DIRECTION)

  CI_INTCONST("SQL_ODBC_API_CONFORMANCE",SQL_ODBC_API_CONFORMANCE)

  CI_INTCONST("SQL_ODBC_VER",SQL_ODBC_VER)

  CI_INTCONST("SQL_ROW_UPDATES",SQL_ROW_UPDATES)

  CI_INTCONST("SQL_ODBC_SAG_CLI_CONFORMANCE",SQL_ODBC_SAG_CLI_CONFORMANCE)

  CI_INTCONST("SQL_SERVER_NAME",SQL_SERVER_NAME)

  CI_INTCONST("SQL_SEARCH_PATTERN_ESCAPE",SQL_SEARCH_PATTERN_ESCAPE)

  CI_INTCONST("SQL_ODBC_SQL_CONFORMANCE",SQL_ODBC_SQL_CONFORMANCE)

  CI_INTCONST("SQL_DBMS_NAME",SQL_DBMS_NAME)

  CI_INTCONST("SQL_DBMS_VER",SQL_DBMS_VER)

  CI_INTCONST("SQL_ACCESSIBLE_TABLES",SQL_ACCESSIBLE_TABLES)

  CI_INTCONST("SQL_ACCESSIBLE_PROCEDURES",SQL_ACCESSIBLE_PROCEDURES)

  CI_INTCONST("SQL_PROCEDURES",SQL_PROCEDURES)

  CI_INTCONST("SQL_CONCAT_NULL_BEHAVIOR",SQL_CONCAT_NULL_BEHAVIOR)

  CI_INTCONST("SQL_CURSOR_COMMIT_BEHAVIOR",SQL_CURSOR_COMMIT_BEHAVIOR)

  CI_INTCONST("SQL_CURSOR_ROLLBACK_BEHAVIOR",SQL_CURSOR_ROLLBACK_BEHAVIOR)

  CI_INTCONST("SQL_DATA_SOURCE_READ_ONLY",SQL_DATA_SOURCE_READ_ONLY)

  CI_INTCONST("SQL_DEFAULT_TXN_ISOLATION",SQL_DEFAULT_TXN_ISOLATION)

  CI_INTCONST("SQL_EXPRESSIONS_IN_ORDERBY",SQL_EXPRESSIONS_IN_ORDERBY)

  CI_INTCONST("SQL_IDENTIFIER_CASE",SQL_IDENTIFIER_CASE)

  CI_INTCONST("SQL_IDENTIFIER_QUOTE_CHAR",SQL_IDENTIFIER_QUOTE_CHAR)

  CI_INTCONST("SQL_MAX_COLUMN_NAME_LEN",SQL_MAX_COLUMN_NAME_LEN)

  CI_INTCONST("SQL_MAX_CURSOR_NAME_LEN",SQL_MAX_CURSOR_NAME_LEN)

  CI_INTCONST("SQL_MAX_OWNER_NAME_LEN",SQL_MAX_OWNER_NAME_LEN)

  CI_INTCONST("SQL_MAX_PROCEDURE_NAME_LEN",SQL_MAX_PROCEDURE_NAME_LEN)

  CI_INTCONST("SQL_MAX_QUALIFIER_NAME_LEN",SQL_MAX_QUALIFIER_NAME_LEN)

  CI_INTCONST("SQL_MAX_TABLE_NAME_LEN",SQL_MAX_TABLE_NAME_LEN)

  CI_INTCONST("SQL_MULT_RESULT_SETS",SQL_MULT_RESULT_SETS)

  CI_INTCONST("SQL_MULTIPLE_ACTIVE_TXN",SQL_MULTIPLE_ACTIVE_TXN)

  CI_INTCONST("SQL_OUTER_JOINS",SQL_OUTER_JOINS)

  CI_INTCONST("SQL_OWNER_TERM",SQL_OWNER_TERM)

  CI_INTCONST("SQL_PROCEDURE_TERM",SQL_PROCEDURE_TERM)

  CI_INTCONST("SQL_QUALIFIER_NAME_SEPARATOR",SQL_QUALIFIER_NAME_SEPARATOR)

  CI_INTCONST("SQL_QUALIFIER_TERM",SQL_QUALIFIER_TERM)

  CI_INTCONST("SQL_SCROLL_CONCURRENCY",SQL_SCROLL_CONCURRENCY)

  CI_INTCONST("SQL_SCROLL_OPTIONS",SQL_SCROLL_OPTIONS)

  CI_INTCONST("SQL_TABLE_TERM",SQL_TABLE_TERM)

  CI_INTCONST("SQL_TXN_CAPABLE",SQL_TXN_CAPABLE)

  CI_INTCONST("SQL_USER_NAME",SQL_USER_NAME)

  CI_INTCONST("SQL_CONVERT_FUNCTIONS",SQL_CONVERT_FUNCTIONS)

  CI_INTCONST("SQL_NUMERIC_FUNCTIONS",SQL_NUMERIC_FUNCTIONS)

  CI_INTCONST("SQL_STRING_FUNCTIONS",SQL_STRING_FUNCTIONS)

  CI_INTCONST("SQL_SYSTEM_FUNCTIONS",SQL_SYSTEM_FUNCTIONS)

  CI_INTCONST("SQL_TIMEDATE_FUNCTIONS",SQL_TIMEDATE_FUNCTIONS)

  CI_INTCONST("SQL_CONVERT_BIGINT",SQL_CONVERT_BIGINT)

  CI_INTCONST("SQL_CONVERT_BINARY",SQL_CONVERT_BINARY)

  CI_INTCONST("SQL_CONVERT_BIT",SQL_CONVERT_BIT)

  CI_INTCONST("SQL_CONVERT_CHAR",SQL_CONVERT_CHAR)

  CI_INTCONST("SQL_CONVERT_DATE",SQL_CONVERT_DATE)

  CI_INTCONST("SQL_CONVERT_DECIMAL",SQL_CONVERT_DECIMAL)

  CI_INTCONST("SQL_CONVERT_DOUBLE",SQL_CONVERT_DOUBLE)

  CI_INTCONST("SQL_CONVERT_FLOAT",SQL_CONVERT_FLOAT)

  CI_INTCONST("SQL_CONVERT_INTEGER",SQL_CONVERT_INTEGER)

  CI_INTCONST("SQL_CONVERT_LONGVARCHAR",SQL_CONVERT_LONGVARCHAR)

  CI_INTCONST("SQL_CONVERT_NUMERIC",SQL_CONVERT_NUMERIC)

  CI_INTCONST("SQL_CONVERT_REAL",SQL_CONVERT_REAL)

  CI_INTCONST("SQL_CONVERT_SMALLINT",SQL_CONVERT_SMALLINT)

  CI_INTCONST("SQL_CONVERT_TIME",SQL_CONVERT_TIME)

  CI_INTCONST("SQL_CONVERT_TIMESTAMP",SQL_CONVERT_TIMESTAMP)

  CI_INTCONST("SQL_CONVERT_TINYINT",SQL_CONVERT_TINYINT)

  CI_INTCONST("SQL_CONVERT_VARBINARY",SQL_CONVERT_VARBINARY)

  CI_INTCONST("SQL_CONVERT_VARCHAR",SQL_CONVERT_VARCHAR)

  CI_INTCONST("SQL_CONVERT_LONGVARBINARY",SQL_CONVERT_LONGVARBINARY)

  CI_INTCONST("SQL_TXN_ISOLATION_OPTION",SQL_TXN_ISOLATION_OPTION)

  CI_INTCONST("SQL_ODBC_SQL_OPT_IEF",SQL_ODBC_SQL_OPT_IEF)

  CI_INTCONST("SQL_CORRELATION_NAME",SQL_CORRELATION_NAME)

  CI_INTCONST("SQL_NON_NULLABLE_COLUMNS",SQL_NON_NULLABLE_COLUMNS)

  CI_INTCONST("SQL_DRIVER_HLIB",SQL_DRIVER_HLIB)

  CI_INTCONST("SQL_DRIVER_ODBC_VER",SQL_DRIVER_ODBC_VER)

  CI_INTCONST("SQL_LOCK_TYPES",SQL_LOCK_TYPES)

  CI_INTCONST("SQL_POS_OPERATIONS",SQL_POS_OPERATIONS)

  CI_INTCONST("SQL_POSITIONED_STATEMENTS",SQL_POSITIONED_STATEMENTS)

  CI_INTCONST("SQL_GETDATA_EXTENSIONS",SQL_GETDATA_EXTENSIONS)

  CI_INTCONST("SQL_BOOKMARK_PERSISTENCE",SQL_BOOKMARK_PERSISTENCE)

  CI_INTCONST("SQL_STATIC_SENSITIVITY",SQL_STATIC_SENSITIVITY)

  CI_INTCONST("SQL_FILE_USAGE",SQL_FILE_USAGE)

  CI_INTCONST("SQL_NULL_COLLATION",SQL_NULL_COLLATION)

  CI_INTCONST("SQL_ALTER_TABLE",SQL_ALTER_TABLE)

  CI_INTCONST("SQL_COLUMN_ALIAS",SQL_COLUMN_ALIAS)

  CI_INTCONST("SQL_GROUP_BY",SQL_GROUP_BY)

  CI_INTCONST("SQL_KEYWORDS",SQL_KEYWORDS)

  CI_INTCONST("SQL_ORDER_BY_COLUMNS_IN_SELECT",SQL_ORDER_BY_COLUMNS_IN_SELECT)

  CI_INTCONST("SQL_OWNER_USAGE",SQL_OWNER_USAGE)

  CI_INTCONST("SQL_QUALIFIER_USAGE",SQL_QUALIFIER_USAGE)

  CI_INTCONST("SQL_QUOTED_IDENTIFIER_CASE",SQL_QUOTED_IDENTIFIER_CASE)

  CI_INTCONST("SQL_SPECIAL_CHARACTERS",SQL_SPECIAL_CHARACTERS)

  CI_INTCONST("SQL_SUBQUERIES",SQL_SUBQUERIES)

  CI_INTCONST("SQL_UNION",SQL_UNION)

  CI_INTCONST("SQL_MAX_COLUMNS_IN_GROUP_BY",SQL_MAX_COLUMNS_IN_GROUP_BY)

  CI_INTCONST("SQL_MAX_COLUMNS_IN_INDEX",SQL_MAX_COLUMNS_IN_INDEX)

  CI_INTCONST("SQL_MAX_COLUMNS_IN_ORDER_BY",SQL_MAX_COLUMNS_IN_ORDER_BY)

  CI_INTCONST("SQL_MAX_COLUMNS_IN_SELECT",SQL_MAX_COLUMNS_IN_SELECT)

  CI_INTCONST("SQL_MAX_COLUMNS_IN_TABLE",SQL_MAX_COLUMNS_IN_TABLE)

  CI_INTCONST("SQL_MAX_INDEX_SIZE",SQL_MAX_INDEX_SIZE)

  CI_INTCONST("SQL_MAX_ROW_SIZE_INCLUDES_LONG",SQL_MAX_ROW_SIZE_INCLUDES_LONG)

  CI_INTCONST("SQL_MAX_ROW_SIZE",SQL_MAX_ROW_SIZE)

  CI_INTCONST("SQL_MAX_STATEMENT_LEN",SQL_MAX_STATEMENT_LEN)

  CI_INTCONST("SQL_MAX_TABLES_IN_SELECT",SQL_MAX_TABLES_IN_SELECT)

  CI_INTCONST("SQL_MAX_USER_NAME_LEN",SQL_MAX_USER_NAME_LEN)

  CI_INTCONST("SQL_MAX_CHAR_LITERAL_LEN",SQL_MAX_CHAR_LITERAL_LEN)

  CI_INTCONST("SQL_TIMEDATE_ADD_INTERVALS",SQL_TIMEDATE_ADD_INTERVALS)

  CI_INTCONST("SQL_TIMEDATE_DIFF_INTERVALS",SQL_TIMEDATE_DIFF_INTERVALS)

  CI_INTCONST("SQL_NEED_LONG_DATA_LEN",SQL_NEED_LONG_DATA_LEN)

  CI_INTCONST("SQL_MAX_BINARY_LITERAL_LEN",SQL_MAX_BINARY_LITERAL_LEN)

  CI_INTCONST("SQL_LIKE_ESCAPE_CLAUSE",SQL_LIKE_ESCAPE_CLAUSE)

  CI_INTCONST("SQL_QUALIFIER_LOCATION",SQL_QUALIFIER_LOCATION)

  CI_INTCONST("SQL_OJ_CAPABILITIES",SQL_OJ_CAPABILITIES)

  CI_INTCONST("SQL_INFO_LAST",SQL_INFO_LAST)

  CI_INTCONST("SQL_INFO_DRIVER_START",SQL_INFO_DRIVER_START)

  CI_INTCONST("SQL_CVT_CHAR",SQL_CVT_CHAR)

  CI_INTCONST("SQL_CVT_NUMERIC",SQL_CVT_NUMERIC)

  CI_INTCONST("SQL_CVT_DECIMAL",SQL_CVT_DECIMAL)

  CI_INTCONST("SQL_CVT_INTEGER",SQL_CVT_INTEGER)

  CI_INTCONST("SQL_CVT_SMALLINT",SQL_CVT_SMALLINT)

  CI_INTCONST("SQL_CVT_FLOAT",SQL_CVT_FLOAT)

  CI_INTCONST("SQL_CVT_REAL",SQL_CVT_REAL)

  CI_INTCONST("SQL_CVT_DOUBLE",SQL_CVT_DOUBLE)

  CI_INTCONST("SQL_CVT_VARCHAR",SQL_CVT_VARCHAR)

  CI_INTCONST("SQL_CVT_LONGVARCHAR",SQL_CVT_LONGVARCHAR)

  CI_INTCONST("SQL_CVT_BINARY",SQL_CVT_BINARY)

  CI_INTCONST("SQL_CVT_VARBINARY",SQL_CVT_VARBINARY)

  CI_INTCONST("SQL_CVT_BIT",SQL_CVT_BIT)

  CI_INTCONST("SQL_CVT_TINYINT",SQL_CVT_TINYINT)

  CI_INTCONST("SQL_CVT_BIGINT",SQL_CVT_BIGINT)

  CI_INTCONST("SQL_CVT_DATE",SQL_CVT_DATE)

  CI_INTCONST("SQL_CVT_TIME",SQL_CVT_TIME)

  CI_INTCONST("SQL_CVT_TIMESTAMP",SQL_CVT_TIMESTAMP)

  CI_INTCONST("SQL_CVT_LONGVARBINARY",SQL_CVT_LONGVARBINARY)

  CI_INTCONST("SQL_FN_CVT_CONVERT",SQL_FN_CVT_CONVERT)

  CI_INTCONST("SQL_FN_STR_CONCAT",SQL_FN_STR_CONCAT)

  CI_INTCONST("SQL_FN_STR_INSERT",SQL_FN_STR_INSERT)

  CI_INTCONST("SQL_FN_STR_LEFT",SQL_FN_STR_LEFT)

  CI_INTCONST("SQL_FN_STR_LTRIM",SQL_FN_STR_LTRIM)

  CI_INTCONST("SQL_FN_STR_LENGTH",SQL_FN_STR_LENGTH)

  CI_INTCONST("SQL_FN_STR_LOCATE",SQL_FN_STR_LOCATE)

  CI_INTCONST("SQL_FN_STR_LCASE",SQL_FN_STR_LCASE)

  CI_INTCONST("SQL_FN_STR_REPEAT",SQL_FN_STR_REPEAT)

  CI_INTCONST("SQL_FN_STR_REPLACE",SQL_FN_STR_REPLACE)

  CI_INTCONST("SQL_FN_STR_RIGHT",SQL_FN_STR_RIGHT)

  CI_INTCONST("SQL_FN_STR_RTRIM",SQL_FN_STR_RTRIM)

  CI_INTCONST("SQL_FN_STR_SUBSTRING",SQL_FN_STR_SUBSTRING)

  CI_INTCONST("SQL_FN_STR_UCASE",SQL_FN_STR_UCASE)

  CI_INTCONST("SQL_FN_STR_ASCII",SQL_FN_STR_ASCII)

  CI_INTCONST("SQL_FN_STR_CHAR",SQL_FN_STR_CHAR)

  CI_INTCONST("SQL_FN_STR_DIFFERENCE",SQL_FN_STR_DIFFERENCE)

  CI_INTCONST("SQL_FN_STR_LOCATE_2",SQL_FN_STR_LOCATE_2)

  CI_INTCONST("SQL_FN_STR_SOUNDEX",SQL_FN_STR_SOUNDEX)

  CI_INTCONST("SQL_FN_STR_SPACE",SQL_FN_STR_SPACE)

  CI_INTCONST("SQL_FN_NUM_ABS",SQL_FN_NUM_ABS)

  CI_INTCONST("SQL_FN_NUM_ACOS",SQL_FN_NUM_ACOS)

  CI_INTCONST("SQL_FN_NUM_ASIN",SQL_FN_NUM_ASIN)

  CI_INTCONST("SQL_FN_NUM_ATAN",SQL_FN_NUM_ATAN)

  CI_INTCONST("SQL_FN_NUM_ATAN2",SQL_FN_NUM_ATAN2)

  CI_INTCONST("SQL_FN_NUM_CEILING",SQL_FN_NUM_CEILING)

  CI_INTCONST("SQL_FN_NUM_COS",SQL_FN_NUM_COS)

  CI_INTCONST("SQL_FN_NUM_COT",SQL_FN_NUM_COT)

  CI_INTCONST("SQL_FN_NUM_EXP",SQL_FN_NUM_EXP)

  CI_INTCONST("SQL_FN_NUM_FLOOR",SQL_FN_NUM_FLOOR)

  CI_INTCONST("SQL_FN_NUM_LOG",SQL_FN_NUM_LOG)

  CI_INTCONST("SQL_FN_NUM_MOD",SQL_FN_NUM_MOD)

  CI_INTCONST("SQL_FN_NUM_SIGN",SQL_FN_NUM_SIGN)

  CI_INTCONST("SQL_FN_NUM_SIN",SQL_FN_NUM_SIN)

  CI_INTCONST("SQL_FN_NUM_SQRT",SQL_FN_NUM_SQRT)

  CI_INTCONST("SQL_FN_NUM_TAN",SQL_FN_NUM_TAN)

  CI_INTCONST("SQL_FN_NUM_PI",SQL_FN_NUM_PI)

  CI_INTCONST("SQL_FN_NUM_RAND",SQL_FN_NUM_RAND)

  CI_INTCONST("SQL_FN_NUM_DEGREES",SQL_FN_NUM_DEGREES)

  CI_INTCONST("SQL_FN_NUM_LOG10",SQL_FN_NUM_LOG10)

  CI_INTCONST("SQL_FN_NUM_POWER",SQL_FN_NUM_POWER)

  CI_INTCONST("SQL_FN_NUM_RADIANS",SQL_FN_NUM_RADIANS)

  CI_INTCONST("SQL_FN_NUM_ROUND",SQL_FN_NUM_ROUND)

  CI_INTCONST("SQL_FN_NUM_TRUNCATE",SQL_FN_NUM_TRUNCATE)

  CI_INTCONST("SQL_FN_TD_NOW",SQL_FN_TD_NOW)

  CI_INTCONST("SQL_FN_TD_CURDATE",SQL_FN_TD_CURDATE)

  CI_INTCONST("SQL_FN_TD_DAYOFMONTH",SQL_FN_TD_DAYOFMONTH)

  CI_INTCONST("SQL_FN_TD_DAYOFWEEK",SQL_FN_TD_DAYOFWEEK)

  CI_INTCONST("SQL_FN_TD_DAYOFYEAR",SQL_FN_TD_DAYOFYEAR)

  CI_INTCONST("SQL_FN_TD_MONTH",SQL_FN_TD_MONTH)

  CI_INTCONST("SQL_FN_TD_QUARTER",SQL_FN_TD_QUARTER)

  CI_INTCONST("SQL_FN_TD_WEEK",SQL_FN_TD_WEEK)

  CI_INTCONST("SQL_FN_TD_YEAR",SQL_FN_TD_YEAR)

  CI_INTCONST("SQL_FN_TD_CURTIME",SQL_FN_TD_CURTIME)

  CI_INTCONST("SQL_FN_TD_HOUR",SQL_FN_TD_HOUR)

  CI_INTCONST("SQL_FN_TD_MINUTE",SQL_FN_TD_MINUTE)

  CI_INTCONST("SQL_FN_TD_SECOND",SQL_FN_TD_SECOND)

  CI_INTCONST("SQL_FN_TD_TIMESTAMPADD",SQL_FN_TD_TIMESTAMPADD)

  CI_INTCONST("SQL_FN_TD_TIMESTAMPDIFF",SQL_FN_TD_TIMESTAMPDIFF)

  CI_INTCONST("SQL_FN_TD_DAYNAME",SQL_FN_TD_DAYNAME)

  CI_INTCONST("SQL_FN_TD_MONTHNAME",SQL_FN_TD_MONTHNAME)

  CI_INTCONST("SQL_FN_SYS_USERNAME",SQL_FN_SYS_USERNAME)

  CI_INTCONST("SQL_FN_SYS_DBNAME",SQL_FN_SYS_DBNAME)

  CI_INTCONST("SQL_FN_SYS_IFNULL",SQL_FN_SYS_IFNULL)

  CI_INTCONST("SQL_FN_TSI_FRAC_SECOND",SQL_FN_TSI_FRAC_SECOND)

  CI_INTCONST("SQL_FN_TSI_SECOND",SQL_FN_TSI_SECOND)

  CI_INTCONST("SQL_FN_TSI_MINUTE",SQL_FN_TSI_MINUTE)

  CI_INTCONST("SQL_FN_TSI_HOUR",SQL_FN_TSI_HOUR)

  CI_INTCONST("SQL_FN_TSI_DAY",SQL_FN_TSI_DAY)

  CI_INTCONST("SQL_FN_TSI_WEEK",SQL_FN_TSI_WEEK)

  CI_INTCONST("SQL_FN_TSI_MONTH",SQL_FN_TSI_MONTH)

  CI_INTCONST("SQL_FN_TSI_QUARTER",SQL_FN_TSI_QUARTER)

  CI_INTCONST("SQL_FN_TSI_YEAR",SQL_FN_TSI_YEAR)

  CI_INTCONST("SQL_OAC_NONE",SQL_OAC_NONE)

  CI_INTCONST("SQL_OAC_LEVEL1",SQL_OAC_LEVEL1)

  CI_INTCONST("SQL_OAC_LEVEL2",SQL_OAC_LEVEL2)

  CI_INTCONST("SQL_OSCC_NOT_COMPLIANT",SQL_OSCC_NOT_COMPLIANT)

  CI_INTCONST("SQL_OSCC_COMPLIANT",SQL_OSCC_COMPLIANT)

  CI_INTCONST("SQL_OSC_MINIMUM",SQL_OSC_MINIMUM)

  CI_INTCONST("SQL_OSC_CORE",SQL_OSC_CORE)

  CI_INTCONST("SQL_OSC_EXTENDED",SQL_OSC_EXTENDED)

  CI_INTCONST("SQL_CB_NULL",SQL_CB_NULL)

  CI_INTCONST("SQL_CB_NON_NULL",SQL_CB_NON_NULL)

  CI_INTCONST("SQL_CB_DELETE",SQL_CB_DELETE)

  CI_INTCONST("SQL_CB_CLOSE",SQL_CB_CLOSE)

  CI_INTCONST("SQL_CB_PRESERVE",SQL_CB_PRESERVE)

  CI_INTCONST("SQL_IC_UPPER",SQL_IC_UPPER)

  CI_INTCONST("SQL_IC_LOWER",SQL_IC_LOWER)

  CI_INTCONST("SQL_IC_SENSITIVE",SQL_IC_SENSITIVE)

  CI_INTCONST("SQL_IC_MIXED",SQL_IC_MIXED)

  CI_INTCONST("SQL_TC_NONE",SQL_TC_NONE)

  CI_INTCONST("SQL_TC_DML",SQL_TC_DML)

  CI_INTCONST("SQL_TC_ALL",SQL_TC_ALL)

  CI_INTCONST("SQL_TC_DDL_COMMIT",SQL_TC_DDL_COMMIT)

  CI_INTCONST("SQL_TC_DDL_IGNORE",SQL_TC_DDL_IGNORE)

  CI_INTCONST("SQL_SO_FORWARD_ONLY",SQL_SO_FORWARD_ONLY)

  CI_INTCONST("SQL_SO_KEYSET_DRIVEN",SQL_SO_KEYSET_DRIVEN)

  CI_INTCONST("SQL_SO_DYNAMIC",SQL_SO_DYNAMIC)

  CI_INTCONST("SQL_SO_MIXED",SQL_SO_MIXED)

  CI_INTCONST("SQL_SO_STATIC",SQL_SO_STATIC)

  CI_INTCONST("SQL_SCCO_READ_ONLY",SQL_SCCO_READ_ONLY)

  CI_INTCONST("SQL_SCCO_LOCK",SQL_SCCO_LOCK)

  CI_INTCONST("SQL_SCCO_OPT_ROWVER",SQL_SCCO_OPT_ROWVER)

  CI_INTCONST("SQL_SCCO_OPT_VALUES",SQL_SCCO_OPT_VALUES)

  CI_INTCONST("SQL_FD_FETCH_NEXT",SQL_FD_FETCH_NEXT)

  CI_INTCONST("SQL_FD_FETCH_FIRST",SQL_FD_FETCH_FIRST)

  CI_INTCONST("SQL_FD_FETCH_LAST",SQL_FD_FETCH_LAST)

  CI_INTCONST("SQL_FD_FETCH_PRIOR",SQL_FD_FETCH_PRIOR)

  CI_INTCONST("SQL_FD_FETCH_ABSOLUTE",SQL_FD_FETCH_ABSOLUTE)

  CI_INTCONST("SQL_FD_FETCH_RELATIVE",SQL_FD_FETCH_RELATIVE)

  CI_INTCONST("SQL_FD_FETCH_RESUME",SQL_FD_FETCH_RESUME)

  CI_INTCONST("SQL_FD_FETCH_BOOKMARK",SQL_FD_FETCH_BOOKMARK)

  CI_INTCONST("SQL_TXN_READ_UNCOMMITTED",SQL_TXN_READ_UNCOMMITTED)

  CI_INTCONST("SQL_TXN_READ_COMMITTED",SQL_TXN_READ_COMMITTED)

  CI_INTCONST("SQL_TXN_REPEATABLE_READ",SQL_TXN_REPEATABLE_READ)

  CI_INTCONST("SQL_TXN_SERIALIZABLE",SQL_TXN_SERIALIZABLE)

  CI_INTCONST("SQL_TXN_VERSIONING",SQL_TXN_VERSIONING)

  CI_INTCONST("SQL_CN_NONE",SQL_CN_NONE)

  CI_INTCONST("SQL_CN_DIFFERENT",SQL_CN_DIFFERENT)

  CI_INTCONST("SQL_CN_ANY",SQL_CN_ANY)

  CI_INTCONST("SQL_NNC_NULL",SQL_NNC_NULL)

  CI_INTCONST("SQL_NNC_NON_NULL",SQL_NNC_NON_NULL)

  CI_INTCONST("SQL_NC_HIGH",SQL_NC_HIGH)

  CI_INTCONST("SQL_NC_LOW",SQL_NC_LOW)

  CI_INTCONST("SQL_NC_START",SQL_NC_START)

  CI_INTCONST("SQL_NC_END",SQL_NC_END)

  CI_INTCONST("SQL_FILE_NOT_SUPPORTED",SQL_FILE_NOT_SUPPORTED)

  CI_INTCONST("SQL_FILE_TABLE",SQL_FILE_TABLE)

  CI_INTCONST("SQL_FILE_QUALIFIER",SQL_FILE_QUALIFIER)

  CI_INTCONST("SQL_GD_ANY_COLUMN",SQL_GD_ANY_COLUMN)

  CI_INTCONST("SQL_GD_ANY_ORDER",SQL_GD_ANY_ORDER)

  CI_INTCONST("SQL_GD_BLOCK",SQL_GD_BLOCK)

  CI_INTCONST("SQL_GD_BOUND",SQL_GD_BOUND)

  CI_INTCONST("SQL_AT_ADD_COLUMN",SQL_AT_ADD_COLUMN)

  CI_INTCONST("SQL_AT_DROP_COLUMN",SQL_AT_DROP_COLUMN)

  CI_INTCONST("SQL_PS_POSITIONED_DELETE",SQL_PS_POSITIONED_DELETE)

  CI_INTCONST("SQL_PS_POSITIONED_UPDATE",SQL_PS_POSITIONED_UPDATE)

  CI_INTCONST("SQL_PS_SELECT_FOR_UPDATE",SQL_PS_SELECT_FOR_UPDATE)

  CI_INTCONST("SQL_GB_NOT_SUPPORTED",SQL_GB_NOT_SUPPORTED)

  CI_INTCONST("SQL_GB_GROUP_BY_EQUALS_SELECT",SQL_GB_GROUP_BY_EQUALS_SELECT)

  CI_INTCONST("SQL_GB_GROUP_BY_CONTAINS_SELECT",SQL_GB_GROUP_BY_CONTAINS_SELECT)

  CI_INTCONST("SQL_GB_NO_RELATION",SQL_GB_NO_RELATION)

  CI_INTCONST("SQL_OU_DML_STATEMENTS",SQL_OU_DML_STATEMENTS)

  CI_INTCONST("SQL_OU_PROCEDURE_INVOCATION",SQL_OU_PROCEDURE_INVOCATION)

  CI_INTCONST("SQL_OU_TABLE_DEFINITION",SQL_OU_TABLE_DEFINITION)

  CI_INTCONST("SQL_OU_INDEX_DEFINITION",SQL_OU_INDEX_DEFINITION)

  CI_INTCONST("SQL_OU_PRIVILEGE_DEFINITION",SQL_OU_PRIVILEGE_DEFINITION)

  CI_INTCONST("SQL_QU_DML_STATEMENTS",SQL_QU_DML_STATEMENTS)

  CI_INTCONST("SQL_QU_PROCEDURE_INVOCATION",SQL_QU_PROCEDURE_INVOCATION)

  CI_INTCONST("SQL_QU_TABLE_DEFINITION",SQL_QU_TABLE_DEFINITION)

  CI_INTCONST("SQL_QU_INDEX_DEFINITION",SQL_QU_INDEX_DEFINITION)

  CI_INTCONST("SQL_QU_PRIVILEGE_DEFINITION",SQL_QU_PRIVILEGE_DEFINITION)

  CI_INTCONST("SQL_SQ_COMPARISON",SQL_SQ_COMPARISON)

  CI_INTCONST("SQL_SQ_EXISTS",SQL_SQ_EXISTS)

  CI_INTCONST("SQL_SQ_IN",SQL_SQ_IN)

  CI_INTCONST("SQL_SQ_QUANTIFIED",SQL_SQ_QUANTIFIED)

  CI_INTCONST("SQL_SQ_CORRELATED_SUBQUERIES",SQL_SQ_CORRELATED_SUBQUERIES)

  CI_INTCONST("SQL_U_UNION",SQL_U_UNION)

  CI_INTCONST("SQL_U_UNION_ALL",SQL_U_UNION_ALL)

  CI_INTCONST("SQL_BP_CLOSE",SQL_BP_CLOSE)

  CI_INTCONST("SQL_BP_DELETE",SQL_BP_DELETE)

  CI_INTCONST("SQL_BP_DROP",SQL_BP_DROP)

  CI_INTCONST("SQL_BP_TRANSACTION",SQL_BP_TRANSACTION)

  CI_INTCONST("SQL_BP_UPDATE",SQL_BP_UPDATE)

  CI_INTCONST("SQL_BP_OTHER_HSTMT",SQL_BP_OTHER_HSTMT)

  CI_INTCONST("SQL_BP_SCROLL",SQL_BP_SCROLL)

  CI_INTCONST("SQL_SS_ADDITIONS",SQL_SS_ADDITIONS)

  CI_INTCONST("SQL_SS_DELETIONS",SQL_SS_DELETIONS)

  CI_INTCONST("SQL_SS_UPDATES",SQL_SS_UPDATES)

  CI_INTCONST("SQL_LCK_NO_CHANGE",SQL_LCK_NO_CHANGE)

  CI_INTCONST("SQL_LCK_EXCLUSIVE",SQL_LCK_EXCLUSIVE)

  CI_INTCONST("SQL_LCK_UNLOCK",SQL_LCK_UNLOCK)

  CI_INTCONST("SQL_POS_POSITION",SQL_POS_POSITION)

  CI_INTCONST("SQL_POS_REFRESH",SQL_POS_REFRESH)

  CI_INTCONST("SQL_POS_UPDATE",SQL_POS_UPDATE)

  CI_INTCONST("SQL_POS_DELETE",SQL_POS_DELETE)

  CI_INTCONST("SQL_POS_ADD",SQL_POS_ADD)

  CI_INTCONST("SQL_QL_START",SQL_QL_START)

  CI_INTCONST("SQL_QL_END",SQL_QL_END)

  CI_INTCONST("SQL_OJ_LEFT",SQL_OJ_LEFT)

  CI_INTCONST("SQL_OJ_RIGHT",SQL_OJ_RIGHT)

  CI_INTCONST("SQL_OJ_FULL",SQL_OJ_FULL)

  CI_INTCONST("SQL_OJ_NESTED",SQL_OJ_NESTED)

  CI_INTCONST("SQL_OJ_NOT_ORDERED",SQL_OJ_NOT_ORDERED)

  CI_INTCONST("SQL_OJ_INNER",SQL_OJ_INNER)

  CI_INTCONST("SQL_OJ_ALL_COMPARISON_OPS",SQL_OJ_ALL_COMPARISON_OPS)

  CI_INTCONST("SQL_QUERY_TIMEOUT",SQL_QUERY_TIMEOUT)

  CI_INTCONST("SQL_MAX_ROWS",SQL_MAX_ROWS)

  CI_INTCONST("SQL_NOSCAN",SQL_NOSCAN)

  CI_INTCONST("SQL_MAX_LENGTH",SQL_MAX_LENGTH)

  CI_INTCONST("SQL_ASYNC_ENABLE",SQL_ASYNC_ENABLE)

  CI_INTCONST("SQL_BIND_TYPE",SQL_BIND_TYPE)

  CI_INTCONST("SQL_CURSOR_TYPE",SQL_CURSOR_TYPE)

  CI_INTCONST("SQL_CONCURRENCY",SQL_CONCURRENCY)

  CI_INTCONST("SQL_KEYSET_SIZE",SQL_KEYSET_SIZE)

  CI_INTCONST("SQL_ROWSET_SIZE",SQL_ROWSET_SIZE)

  CI_INTCONST("SQL_SIMULATE_CURSOR",SQL_SIMULATE_CURSOR)

  CI_INTCONST("SQL_RETRIEVE_DATA",SQL_RETRIEVE_DATA)

  CI_INTCONST("SQL_USE_BOOKMARKS",SQL_USE_BOOKMARKS)

  CI_INTCONST("SQL_GET_BOOKMARK",SQL_GET_BOOKMARK)

  CI_INTCONST("SQL_ROW_NUMBER",SQL_ROW_NUMBER)

  CI_INTCONST("SQL_STMT_OPT_MAX",SQL_STMT_OPT_MAX)

  CI_INTCONST("SQL_STMT_OPT_MIN",SQL_STMT_OPT_MIN)

  CI_INTCONST("SQL_QUERY_TIMEOUT_DEFAULT",SQL_QUERY_TIMEOUT_DEFAULT)

  CI_INTCONST("SQL_MAX_ROWS_DEFAULT",SQL_MAX_ROWS_DEFAULT)

  CI_INTCONST("SQL_NOSCAN_OFF",SQL_NOSCAN_OFF)

  CI_INTCONST("SQL_NOSCAN_ON",SQL_NOSCAN_ON)

  CI_INTCONST("SQL_NOSCAN_DEFAULT",SQL_NOSCAN_DEFAULT)

  CI_INTCONST("SQL_MAX_LENGTH_DEFAULT",SQL_MAX_LENGTH_DEFAULT)

  CI_INTCONST("SQL_ASYNC_ENABLE_OFF",SQL_ASYNC_ENABLE_OFF)

  CI_INTCONST("SQL_ASYNC_ENABLE_ON",SQL_ASYNC_ENABLE_ON)

  CI_INTCONST("SQL_ASYNC_ENABLE_DEFAULT",SQL_ASYNC_ENABLE_DEFAULT)

  CI_INTCONST("SQL_BIND_BY_COLUMN",SQL_BIND_BY_COLUMN)

  CI_INTCONST("SQL_BIND_TYPE_DEFAULT",SQL_BIND_TYPE_DEFAULT)

  CI_INTCONST("SQL_CONCUR_READ_ONLY",SQL_CONCUR_READ_ONLY)

  CI_INTCONST("SQL_CONCUR_LOCK",SQL_CONCUR_LOCK)

  CI_INTCONST("SQL_CONCUR_ROWVER",SQL_CONCUR_ROWVER)

  CI_INTCONST("SQL_CONCUR_VALUES",SQL_CONCUR_VALUES)

  CI_INTCONST("SQL_CONCUR_DEFAULT",SQL_CONCUR_DEFAULT)

  CI_INTCONST("SQL_CURSOR_FORWARD_ONLY",SQL_CURSOR_FORWARD_ONLY)

  CI_INTCONST("SQL_CURSOR_KEYSET_DRIVEN",SQL_CURSOR_KEYSET_DRIVEN)

  CI_INTCONST("SQL_CURSOR_DYNAMIC",SQL_CURSOR_DYNAMIC)

  CI_INTCONST("SQL_CURSOR_STATIC",SQL_CURSOR_STATIC)

  CI_INTCONST("SQL_CURSOR_TYPE_DEFAULT",SQL_CURSOR_TYPE_DEFAULT)

  CI_INTCONST("SQL_ROWSET_SIZE_DEFAULT",SQL_ROWSET_SIZE_DEFAULT)

  CI_INTCONST("SQL_KEYSET_SIZE_DEFAULT",SQL_KEYSET_SIZE_DEFAULT)

  CI_INTCONST("SQL_SC_NON_UNIQUE",SQL_SC_NON_UNIQUE)

  CI_INTCONST("SQL_SC_TRY_UNIQUE",SQL_SC_TRY_UNIQUE)

  CI_INTCONST("SQL_SC_UNIQUE",SQL_SC_UNIQUE)

  CI_INTCONST("SQL_RD_OFF",SQL_RD_OFF)

  CI_INTCONST("SQL_RD_ON",SQL_RD_ON)

  CI_INTCONST("SQL_RD_DEFAULT",SQL_RD_DEFAULT)

  CI_INTCONST("SQL_UB_OFF",SQL_UB_OFF)

  CI_INTCONST("SQL_UB_ON",SQL_UB_ON)

  CI_INTCONST("SQL_UB_DEFAULT",SQL_UB_DEFAULT)

  CI_INTCONST("SQL_ACCESS_MODE",SQL_ACCESS_MODE)

  CI_INTCONST("SQL_AUTOCOMMIT",SQL_AUTOCOMMIT)

  CI_INTCONST("SQL_LOGIN_TIMEOUT",SQL_LOGIN_TIMEOUT)

  CI_INTCONST("SQL_OPT_TRACE",SQL_OPT_TRACE)

  CI_INTCONST("SQL_OPT_TRACEFILE",SQL_OPT_TRACEFILE)

  CI_INTCONST("SQL_TRANSLATE_DLL",SQL_TRANSLATE_DLL)

  CI_INTCONST("SQL_TRANSLATE_OPTION",SQL_TRANSLATE_OPTION)

  CI_INTCONST("SQL_TXN_ISOLATION",SQL_TXN_ISOLATION)

  CI_INTCONST("SQL_CURRENT_QUALIFIER",SQL_CURRENT_QUALIFIER)

  CI_INTCONST("SQL_ODBC_CURSORS",SQL_ODBC_CURSORS)

  CI_INTCONST("SQL_QUIET_MODE",SQL_QUIET_MODE)

  CI_INTCONST("SQL_PACKET_SIZE",SQL_PACKET_SIZE)

  CI_INTCONST("SQL_CONN_OPT_MAX",SQL_CONN_OPT_MAX)

  CI_INTCONST("SQL_CONNECT_OPT_DRVR_START",SQL_CONNECT_OPT_DRVR_START)

  CI_INTCONST("SQL_CONN_OPT_MIN",SQL_CONN_OPT_MIN)

  CI_INTCONST("SQL_MODE_READ_WRITE",SQL_MODE_READ_WRITE)

  CI_INTCONST("SQL_MODE_READ_ONLY",SQL_MODE_READ_ONLY)

  CI_INTCONST("SQL_MODE_DEFAULT",SQL_MODE_DEFAULT)

  CI_INTCONST("SQL_AUTOCOMMIT_OFF",SQL_AUTOCOMMIT_OFF)

  CI_INTCONST("SQL_AUTOCOMMIT_ON",SQL_AUTOCOMMIT_ON)

  CI_INTCONST("SQL_AUTOCOMMIT_DEFAULT",SQL_AUTOCOMMIT_DEFAULT)

  CI_INTCONST("SQL_LOGIN_TIMEOUT_DEFAULT",SQL_LOGIN_TIMEOUT_DEFAULT)

  CI_INTCONST("SQL_OPT_TRACE_OFF",SQL_OPT_TRACE_OFF)

  CI_INTCONST("SQL_OPT_TRACE_ON",SQL_OPT_TRACE_ON)

  CI_INTCONST("SQL_OPT_TRACE_DEFAULT",SQL_OPT_TRACE_DEFAULT)

  CI_STRINGCONST("SQL_OPT_TRACE_FILE_DEFAULT",SQL_OPT_TRACE_FILE_DEFAULT)

  CI_INTCONST("SQL_CUR_USE_IF_NEEDED",SQL_CUR_USE_IF_NEEDED)

  CI_INTCONST("SQL_CUR_USE_ODBC",SQL_CUR_USE_ODBC)

  CI_INTCONST("SQL_CUR_USE_DRIVER",SQL_CUR_USE_DRIVER)

  CI_INTCONST("SQL_CUR_DEFAULT",SQL_CUR_DEFAULT)

  CI_INTCONST("SQL_BEST_ROWID",SQL_BEST_ROWID)

  CI_INTCONST("SQL_ROWVER",SQL_ROWVER)

  CI_INTCONST("SQL_SCOPE_CURROW",SQL_SCOPE_CURROW)

  CI_INTCONST("SQL_SCOPE_TRANSACTION",SQL_SCOPE_TRANSACTION)

  CI_INTCONST("SQL_SCOPE_SESSION",SQL_SCOPE_SESSION)

  CI_INTCONST("SQL_ENTIRE_ROWSET",SQL_ENTIRE_ROWSET)

  CI_INTCONST("SQL_POSITION",SQL_POSITION)

  CI_INTCONST("SQL_REFRESH",SQL_REFRESH)

  CI_INTCONST("SQL_UPDATE",SQL_UPDATE)

  CI_INTCONST("SQL_DELETE",SQL_DELETE)

  CI_INTCONST("SQL_ADD",SQL_ADD)

  CI_INTCONST("SQL_LOCK_NO_CHANGE",SQL_LOCK_NO_CHANGE)

  CI_INTCONST("SQL_LOCK_EXCLUSIVE",SQL_LOCK_EXCLUSIVE)

  CI_INTCONST("SQL_LOCK_UNLOCK",SQL_LOCK_UNLOCK)

  CI_STRINGCONST("SQL_ODBC_KEYWORDS",SQL_ODBC_KEYWORDS)

  CI_INTCONST("SQL_FETCH_NEXT",SQL_FETCH_NEXT)

  CI_INTCONST("SQL_FETCH_FIRST",SQL_FETCH_FIRST)

  CI_INTCONST("SQL_FETCH_LAST",SQL_FETCH_LAST)

  CI_INTCONST("SQL_FETCH_PRIOR",SQL_FETCH_PRIOR)

  CI_INTCONST("SQL_FETCH_ABSOLUTE",SQL_FETCH_ABSOLUTE)

  CI_INTCONST("SQL_FETCH_RELATIVE",SQL_FETCH_RELATIVE)

  CI_INTCONST("SQL_FETCH_BOOKMARK",SQL_FETCH_BOOKMARK)

  CI_INTCONST("SQL_ROW_SUCCESS",SQL_ROW_SUCCESS)

  CI_INTCONST("SQL_ROW_DELETED",SQL_ROW_DELETED)

  CI_INTCONST("SQL_ROW_UPDATED",SQL_ROW_UPDATED)

  CI_INTCONST("SQL_ROW_NOROW",SQL_ROW_NOROW)

  CI_INTCONST("SQL_ROW_ADDED",SQL_ROW_ADDED)

  CI_INTCONST("SQL_ROW_ERROR",SQL_ROW_ERROR)

  CI_INTCONST("SQL_CASCADE",SQL_CASCADE)

  CI_INTCONST("SQL_RESTRICT",SQL_RESTRICT)

  CI_INTCONST("SQL_SET_NULL",SQL_SET_NULL)

  CI_INTCONST("SQL_PARAM_TYPE_UNKNOWN",SQL_PARAM_TYPE_UNKNOWN)

  CI_INTCONST("SQL_PARAM_INPUT",SQL_PARAM_INPUT)

  CI_INTCONST("SQL_PARAM_INPUT_OUTPUT",SQL_PARAM_INPUT_OUTPUT)

  CI_INTCONST("SQL_RESULT_COL",SQL_RESULT_COL)

  CI_INTCONST("SQL_PARAM_OUTPUT",SQL_PARAM_OUTPUT)

  CI_INTCONST("SQL_RETURN_VALUE",SQL_RETURN_VALUE)

  CI_INTCONST("SQL_PARAM_TYPE_DEFAULT",SQL_PARAM_TYPE_DEFAULT)

  CI_INTCONST("SQL_SETPARAM_VALUE_MAX",SQL_SETPARAM_VALUE_MAX)

  CI_INTCONST("SQL_INDEX_UNIQUE",SQL_INDEX_UNIQUE)

  CI_INTCONST("SQL_INDEX_ALL",SQL_INDEX_ALL)

  CI_INTCONST("SQL_QUICK",SQL_QUICK)

  CI_INTCONST("SQL_ENSURE",SQL_ENSURE)

  CI_INTCONST("SQL_TABLE_STAT",SQL_TABLE_STAT)

  CI_INTCONST("SQL_INDEX_CLUSTERED",SQL_INDEX_CLUSTERED)

  CI_INTCONST("SQL_INDEX_HASHED",SQL_INDEX_HASHED)

  CI_INTCONST("SQL_INDEX_OTHER",SQL_INDEX_OTHER)

  CI_INTCONST("SQL_PT_UNKNOWN",SQL_PT_UNKNOWN)

  CI_INTCONST("SQL_PT_PROCEDURE",SQL_PT_PROCEDURE)

  CI_INTCONST("SQL_PT_FUNCTION",SQL_PT_FUNCTION)

  CI_INTCONST("SQL_PC_UNKNOWN",SQL_PC_UNKNOWN)

  CI_INTCONST("SQL_PC_NOT_PSEUDO",SQL_PC_NOT_PSEUDO)

  CI_INTCONST("SQL_PC_PSEUDO",SQL_PC_PSEUDO)

  CI_INTCONST("SQL_DATABASE_NAME",SQL_DATABASE_NAME)

  CI_INTCONST("SQL_FD_FETCH_PREV",SQL_FD_FETCH_PREV)

  CI_INTCONST("SQL_FETCH_PREV",SQL_FETCH_PREV)

  CI_INTCONST("SQL_CONCUR_TIMESTAMP",SQL_CONCUR_TIMESTAMP)

  CI_INTCONST("SQL_SCCO_OPT_TIMESTAMP",SQL_SCCO_OPT_TIMESTAMP)

  CI_INTCONST("SQL_CC_DELETE",SQL_CC_DELETE)

  CI_INTCONST("SQL_CR_DELETE",SQL_CR_DELETE)

  CI_INTCONST("SQL_CC_CLOSE",SQL_CC_CLOSE)

  CI_INTCONST("SQL_CR_CLOSE",SQL_CR_CLOSE)

  CI_INTCONST("SQL_CC_PRESERVE",SQL_CC_PRESERVE)

  CI_INTCONST("SQL_CR_PRESERVE",SQL_CR_PRESERVE)

  CI_INTCONST("SQL_FETCH_RESUME",SQL_FETCH_RESUME)

  CI_INTCONST("SQL_SCROLL_FORWARD_ONLY",SQL_SCROLL_FORWARD_ONLY)

  CI_INTCONST("SQL_SCROLL_KEYSET_DRIVEN",SQL_SCROLL_KEYSET_DRIVEN)

  CI_INTCONST("SQL_SCROLL_DYNAMIC",SQL_SCROLL_DYNAMIC)

  CI_INTCONST("SQL_SCROLL_STATIC",SQL_SCROLL_STATIC)

  CI_INTCONST("SQL_PC_NON_PSEUDO",SQL_PC_NON_PSEUDO)

}

extern void odbc_compact_init(void);

extern void odbc2_init(void);

extern void odbc3_init(void);

void odbc_init(void)

{

	odbc_compact_init();

	odbc2_init();

	odbc3_init();



}

